aurutils/aurutils

- doc/aurbuild.md
- doc/aurchain.md
- doc/aurqueue.md
- doc/aursearch.md
- doc/aursync.md
- doc/repofind.md
- doc/repoman.md
A start for the documentation to solve #76. I would like to get some feedback on the factual accuracy and what would be the best way to get this into groff format. I did not change the documentation for aursift and did not document aursplit. Aurqueue is also sparsely documented.
> Start for man pages for all scripts except aursift.

- bin/aurchain
- bin/aurcheck
- bin/aursearch
- bin/aursync
> replace jshon with jq

- bin/aursearch
- bin/aursync
- man1/aursearch.1
> #150 & #156

- bin/aurbuild
This fixes 2 bugs that caused aurbuild to fail when creating a new container (introduced in 1.3.3)
> Fix aurbuild fail on creating a new container

- man1/aurchain.1
- man1/aurcheck.1
- man1/aursearch.1
- man1/aursync.1
> man1: Update See also section

- man1/aurcheck.1
The doc for -c is probably not good enough. Didn't get anything out of it when trying to see how it works.
Signed-off-by: Morten Linderud <morten@linderud.pw>
> Fixed aurcheck manpage

- bin/aurchain
- bin/aursift
- bin/aursync
> shellcheck 0.4.6

- bin/aurbuild_chroot
- man1/aurbuild_chroot.1
Completes a few tasks in #217. Feedback appreciated before working on more documentation in the future.
> aurbuild_chroot documentation

- bin/aurfetch
> aurfetch: specify git work-tree/git-dir

- lib/aur-fetch
- lib/aur-rpc
- lib/aur-sync
- makepkg/PKGBUILD
Usually I would update the documentation, but there's none present for `aur-fetch` anyway. (@Foxboron)
> sync: AURURI variable

- lib/aur-search
> aur-search: Fix order of fields so that votes are correctly shown

- lib/aur-build
This does not cover chroot builds for now. Fixes #264
> aur-build: display status on failed build

- lib/aur-build
https://github.com/AladW/aurutils/commit/c02912390135c6aad570117ab9440eb420bc5a4d is good, except for this typo 😉
> aur-build: Fix summary (#264)

- lib/aur-sync
- man1/aur-sync.1
> aur-sync: --nover-shallow

- lib/aur-fetch-snapshot
- lib/aur-jobs
- lib/aur-rpc
- lib/aur-srcver
- lib/aur-sync
- lib/aur-vercmp
- makepkg/PKGBUILD
> Use parallel instead of xargs (#391)

- lib/aur-build
- lib/aur-chroot
- man1/aur-chroot.1
> aur-chroot: allow using repos from specified pacman.conf

- lib/aur-fetch-git
- lib/aur-fetch-snapshot
This ended up being much easier than I expected.
Fixes #399
> aur-fetch: show diff to PKGBUILD first

- lib/aur-sync
> aur-sync: print dependencies by queue order

- lib/aur-chroot
- lib/aur-vercmp
- man1/aur-vercmp.1
> aur-chroot: bind-mount all file:// paths

- lib/aur-vercmp
- man1/aur-vercmp.1
> aur-vercmp: remove remainders of -d

- man1/aur-depends.1
- man1/aur-fetch.1
- man1/aur-graph.1
- man1/aur-pkglist.1
- man1/aur-search.1
- man1/aur-srcver.1
- man1/aur-sync.1
- man1/aur-vercmp-devel.1
- man1/aur.1
* Mention `aur-repo` and `aur-vercmp-devel`
* Use imperative
* Use description provided in sub-man-pages
* Use Aurweb instead of AurJson
Fixes #480
> Update and sync aur.1

- lib/aur-build
- lib/aur-chroot
- lib/aur-fetch
- lib/aur-fetch-git
- lib/aur-fetch-snapshot
- lib/aur-pkglist
- lib/aur-repo
- lib/aur-repo-filter
- lib/aur-rpc
- lib/aur-search
- lib/aur-sync
- lib/aur-vercmp
Some more documentation stuff:
* sort flags
* use `<repo>` and `<path>` more consistently
* remove `-h` / `--help` flags
* remove unused flags
> Make usage outputs more uniform

- Makefile
- completions/Makefile
- completions/bash/aurutils.in
- completions/command_opts.m4
- completions/zsh/aurutils.in
Add initial zsh completion implementation.
Signed-off-by: Joey Pabalinas <joeypabalinas@gmail.com>
> Add _aur zsh completion code

- lib/aur-chroot
- lib/aur-repo
> Added pacman.conf overrides to aur-chroot and aur-repo

- lib/aur-build
- lib/aur-chroot
- lib/aur-depends
- lib/aur-fetch
- lib/aur-pkglist
- lib/aur-repo
- lib/aur-repo-filter
- lib/aur-rpc
- lib/aur-search
- lib/aur-srcver
- lib/aur-sync
- lib/aur-vercmp
Make the usage function print the usage string to stderr and
exit with error.
> make the usage function consistent across scripts

- lib/aur-fetch
Available formats:
- log: show all commits between HEAD and last seen.
- diff: show differences between HEAD and last seen.
> fetch: Change patch format

- lib/aur-repo-filter
- man1/aur-repo-filter.1
https://github.com/andrewgregory/pacutils/issues/26 was fixed so this option can now be safely exposed.
> aur-repo-filter: expose --sysroot

- lib/aur-fetch
- man1/aur-fetch.1
> fetch: add diff format

- lib/aur-build
- lib/aur-fetch
- lib/aur-repo-filter
- lib/aur-sync
- man1/aur-build.1
This fixes in particular a regression introduced in #654:
```
aur-repo: option '--pacman-conf' requires an argument
```
> scripts: miscellaneous fixes

- lib/aur-build
- lib/aur-chroot
https://github.com/AladW/aurutils/pull/664#issuecomment-575911684 and following discussion
> aur-build: fixes for #664

- lib/aur-build
- lib/aur-chroot
Rationale for #666 :smiling_imp:  explained in #655 in [this comment.](https://github.com/AladW/aurutils/issues/665#issuecomment-576718516)
> Fix aur-build -D flag.

- README.md
- man1/aur-build.1
- man1/aur.1
Something like this @AladW? 🙂 
I've tried to guess the syntax of man files but I'm not actually sure how to check if it's good...?
> Remove "See also" from README, add rebuild-detector to man examples

- lib/aur-sync
> Fix empty lines in ignore file

- lib/aur-sync
> s/aur_graph/aur graph/

- lib/aur-search
Unset LC_ALL just for that printf.
Discussed here: AladW#686 (comment)
> Ignore LC_ALL whe setting LC_NUMERIC.

- lib/aur-build
- lib/aur-repo
https://bbs.archlinux.org/viewtopic.php?pid=1883951#p1883951
> aur-repo: print resolved path

- lib/aur-query
- test/issue-706
Fix for #706 
Leaving this as a draft as I am still uncertain how the wget didn't have this issue.
> Fix "warning: 'url' requires parameter"

- lib/aur-sync
- man1/aur-sync.1
> aur-fetch: pass on EOF to aur-depends

- lib/aur-build
- lib/aur-chroot
- man1/aur-build.1
> aur-build: pass on --syncdeps to pkgver makepkg

- lib/aur-repo
> aur-repo: do not try to extract an empty database

- man1/aur-build.1
- man1/aur-chroot.1
- man1/aur-repo-filter.1
- man1/aur-repo.1
Documentation updates for 3.0.0. `aur-query(1)` is still missing.
> man1: update documentation

- LICENSE
- lib/aur-build
As https://github.com/AladW/aurutils/commit/306ff632557d37dc70125b98d24ea45bdbb80517 but for `aur-build`.
Also remove some redundancy for the "Running..." messages.
> aur-build: do not print results to stdout

- lib/aur-build
- makepkg/PKGBUILD
- man1/aur-build.1
- man1/aur-chroot.1
Also includes a fix for supporting `PACMAN` with `--pacman-conf`.
> aur-build: support MAKEPKG environment variable

- lib/aur-build
- lib/aur-query
- tests/issue/085
- tests/issue/216
- tests/issue/378
- tests/issue/513
- tests/issue/636
- tests/issue/714
- tests/issue/741
- tests/package-test
https://github.com/AladW/aurutils/pull/763/commits/745ce12005bc1a650f66ac3166fc9e9fdf4a4b8a forgot the second `-v`.
Make some other small adjustments to tests and `aur-build` for the `3.0` release.
> aur-query: fix awk command-line

- man1/aur-build.1
> aur-build.1: mention limitations of auto-key-retrieve

- lib/aur-sync
> Add --suffix option to aur sync

- lib/aur-build
- lib/aur-depends
- lib/aur-query
- lib/aur-search
- lib/aur-srcver
- lib/aur-sync
- lib/aur-vercmp
> lib: use /tmp/aurutils/$UID for temporary files

- ISSUE_TEMPLATE.md
- README.md
- lib/aur-repo
- makepkg/aurutils.changelog
- man1/aur-build.1
- man1/aur-chroot.1
- man1/aur-graph.1
- man1/aur-repo.1
- man1/aur.1
- tests/package-test
Fixes #782 
Fixes #784 
Fixes #785
> aurutils: release 3.1

- Makefile
- aur.in
- makepkg/PKGBUILD
- makepkg/aurutils.changelog
> aur: fix substitution of AUR_LIB_DIR

- lib/aur-build
- lib/aur-repo
> aur-build: fix db_name/db_root argument order

- lib/aur-build
> aur-build: add diag_moved_packages()

- .github/workflows/ci.yml
- docker/Dockerfile
> CI: Change image from archlinux/base to archlinux

- lib/aur-build
> aur-build: fix checking for empty path (pacman conf)

- tests/issue/085
- tests/issue/216
- tests/issue/378
- tests/issue/513
- tests/issue/636
- tests/issue/714
- tests/issue/741
I got rate-limited on AUR so I couldn't test everything yet :-(
> tests: update for 3.2

- lib/aur-query
- man1/aur-query.1
Finishing `aur-query.1` has ben long overdue...
> aur-query: support AUR_LOCATION, write man page

- lib/aur-depends
Minor optimization for the common case.
> aur-depends: only write tsv/x as needed

- man7/aurvcs.7
> aurvcs.7: no-ver-shallow -> no-ver-argv

- lib/aur-search
- makepkg/aurutils.changelog
- man1/aur-search.1
- man1/aur.1
Example use case: 
```bash
aur search -m bloatymcbloatface | cut -f2 | sort -u | aur fetch -
```
> aur-search: add --table

- lib/aur-build
- makepkg/aurutils.changelog
- man1/aur-build.1
cf. https://gitlab.archlinux.org/pacman/pacman/-/commit/2535611d6c3cbf951408c50ab35953efaf32f686
> aur-build: support PACMAN_AUTH

- lib/aur-sync
commit f1eb5d4b breaks command-line ignores.
> sync: fix ignore array

- tests/issue/880
- tests/issue/901
> tests: add tests for issue #880, #901

- lib/aur-query
https://github.com/AladW/aurutils/pull/919#issuecomment-1037148568
> query: build JSON manually for union as well

- lib/aur-pkglist
- man1/aur-pkglist.1
> aur-pkglist: add `--verify`

- Makefile
- lib/aur-depends
- makepkg/aurutils.changelog
- tests/package
> depends: filter dependencies (`--no-checkdepends`) earlier

- Makefile
- lib/aur-depends
- lib/aur-search
- lib/aur-sync
- makepkg/aurutils.changelog
- man1/aur-depends.1
- man1/aur-sync.1
> depends, search, sync: add `--optdepends`

- lib/aur-search
- makepkg/aurutils.changelog
> search: set default value for empty array elements

- lib/aur-build
- lib/aur-chroot
- makepkg/aurutils.changelog
- man1/aur-chroot.1
https://github.com/AladW/aurutils/issues/907#issuecomment-1055780519
> chroot: do not exit on chroot creation

- lib/aur-srcver
- makepkg/aurutils.changelog
- man7/aurvcs.7
https://github.com/AladW/aurutils/issues/952#issuecomment-1057192219
> aurvcs.7: implement sample code with `aur-view`

- lib/aur-build
- makepkg/aurutils.changelog
> build: allow secondary repositories for local repo sysupgrade

- lib/aur-build
- lib/aur-build--pkglist
> `build`: sign existing packages, `build--pkglist`

- lib/aur-build
- lib/aur-build--pkglist
- man1/aur-build.1
> `build`: add `--dry-run`

- examples/README.md
- examples/chroot-batch
- lib/aur-build
- makepkg/aurutils.changelog
> examples: add `chroot-batch`

- Makefile
- lib/aur-build
- makepkg/aurutils.changelog
https://github.com/AladW/aurutils/issues/980#issuecomment-1090780107
Solves #980
> aur-build: add `--results-append`, write results file as build user

- lib/aur-build
- lib/aur-repo
- lib/aur-repo-filter
- lib/aur-sync
- man1/aur-repo-filter.1
- man1/aur-repo.1
- man1/aur-search.1
- man1/aur-sync.1
> man1: add missing options

- lib/aur-build
- lib/aur-chroot
- man1/aur-build.1
- man1/aur-chroot.1
https://github.com/AladW/aurutils/issues/985#issuecomment-1108326039
Closes #985
> build, chroot: fixes for command-line options

- completions/zsh/_aur
I could have sworn it worked before, and I know I tested it. I must have made some "cleanup" last time after I tested it and before I committed it. My bad.
> Fix third party completion

- lib/aur-build--sync
- lib/aur-chroot
- makepkg/aurutils.changelog
- man1/aur-chroot.1
> `chroot`: limit `sudo`-specific flags to `sudo`

- Makefile
- lib/aur-build
- lib/aur-srcver
- makepkg/aurutils.changelog
- man1/aur-srcver.1
> `srcver`: accept arbitrary paths to PKGBUILD directories

- lib/aur-build
- makepkg/aurutils.changelog
- man1/aur-build.1
> `build`: allow per-repository `makepkg.conf` in `/etc/aurutils`

- lib/aur-depends
- man1/aur-depends.1
> `depends`: add `--jsonl`

- examples/sync-rebuild
> sync-rebuild: fix database option crash

- lib/aur-sync
> `sync`: apply `--save` when building packages

- examples/sync-rebuild
- makepkg/PKGBUILD
> `sync-rebuild`: expand `--user` home directory

- Makefile
- lib/aur-sync
- makepkg/aurutils.changelog
- tests/issue/1062
> `sync`: remove effect of `AUR_SYNC_USE_NINJA` on `--no-build`

- lib/aur-build
- lib/aur-repo
- makepkg/aurutils.changelog
> `repo`: required configured pacman repository

- lib/aur-depends
- lib/aur-repo
- lib/aur-repo-parse
- lib/aur-sync
- makepkg/aurutils.changelog
- man1/aur-repo.1
- perl/AUR/Depends.pm
- perl/AUR/Repo.pm
Some preliminary work for #1144
> `repo-parse`: add `--ignore`

- lib/aur-repo-parse
- perl/AUR/Repo.pm
- tests/repo-parse
> repo-parse: output [] for no matches

- lib/aur-view
- makepkg/aurutils.changelog
> view: define missing XDG_CONFIG_HOME

- Makefile
- lib/aur-sync--filter
- lib/aurweb/aur-depends
- makepkg/aurutils.changelog
- perl/AUR/Depends.pm
> `Depends.pm`: remove targets recursively with prune()

- Makefile
- lib/pacman/aur-build
- makepkg/aurutils.changelog
> `build`: do not skip on partial results

- lib/pacman/aur-chroot
- makepkg/aurutils.changelog
> chroot: preserve LOGDEST and SRCDEST by default

- lib/pacman/aur-repo
- makepkg/aurutils.changelog
> repo: avoid empty output with -q -u

- lib/pacman/aur-build
This reverts commit e5dced1d74649891c07f15b89cb6a30b14f22809.
Fixes #1204 #1218
> Revert "build: error on partially built package group"

- lib/pacman/aur-chroot
> chroot: preserve `SRCPKGDEST`, `MAKEFLAGS`, `PACKAGER`
