aurutils/aurutils

bin/aurbuild
Update the root chroot once before build so that the user chroot doesn't have to update base packages on each subsequent package build
=> Update chroot once

bin/aurcheck
`aurcheck` raises an error when run with `stdin` open but not connected to a terminal:
```sh
$ 0</dev/null aurcheck -q myrepo        
error: argument '-' specified with empty stdin
aursearch: no targets specified
```
This is due to `pacsift`'s logic for figuring out whether to read packages from `stdin` -- from `man pacsift`:
> CAVEATS
pacsift determines whether or not to read packages from stdin based on a naive check using isatty(3).  If pacsift is called in an environment, such as a shell function or script being used in a pipe, where stdin is not connected to a terminal but does not contain packages to filter, pacsift should be called with stdin closed.  For POSIX-compatible shells, this can be done with "<&-".
This PR adds an explicit `stdin` close so that `pacsift` behaves when …
=> Close stdin when invoking pacsift in aurcheck

bin/aurbuild
Possible workaround to #223. This check also applies to makechrootpkg. Ideally this could be checked for the whole queue before proceeding with the build, but `makepkg --packagelist` only works for a single PKGBUILD.
=> aurbuild: check for built packages

bin/aursrcver
Tiny fix discovered while testing, probably left there by accident:
```
❯ aursrcver ~/.cache/aursync/*-git
alacritty-git   0.1.0.730.gb82622e-1
antigen-git     v2.2.3.r6.gc91f77c-1
aurutils-git    1.5.3.r272.gb84989e-1
dragon-git      r10.24242e7-1
gtk-theme-arc-grey-git  r728.51780e1-1
i3ipc-python-git        r173.1516924861.99cbe2a-1
libva-git       2.0.0.r58.g71fd9ec-1
libva-intel-driver-git  2.0.0.r106.g0b37282-1
lscolors-git    r242.73965bd-1
pam_u2f-git     1.0.4.r76.gb2f46d9-1
py3status-git   3.7.r240.g3a2d0b2a-1
python-azure-git        latest-1
universal-ctags-git     0.r5771.5e4eca42-1
removed '/tmp/tmp.zSnjGOHf5Z'                          <-------- don't need this in my output
```
=> [aursrcver] No verbose rm

bin/aur
Provide a similar mechanism that `git` has for user defined sub-commands.
`git` allows the use of any executable in `$PATH` with prefix `'git-'` to be used with the main `git` command.
E.g. `'git-name'` can be invoked with `$git name`.
In aa59551, I used executables on `$PATH` that were prefixed by `'aur-'`. But in retrospect that was probably a poor choice since [there are already some packages](https://aur.archlinux.org/packages/?K=aur-) which use executables with the `'aur-'` prefix that would end up there.
One alternative is to use another prefix, something like `'aurutils-'`.
Another would be having a dedicated directory for sub-commands scripts. E.g.
```bash
USER_CMDS_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/aurutils/usrcommands
```
Besides giving the user free choice over the naming …
=> aur: allow execution of user defined scripts

lib/aur-build, lib/aur-build-nspawn, lib/aur-deps, lib/aur-deps-rpc, lib/aur-deps-src, lib/aur-fetch, lib/aur-fetch-git, lib/aur-fetch-snapshot, lib/aur-pkglist, lib/aur-rfilter, lib/aur-rpc, lib/aur-search, lib/aur-srcver, lib/aur-sync, lib/aur-vercmp, makepkg/PKGBUILD, man1/aur-build.1, man1/aur-sync.1
This branch removes some unused constructs in a vain attempt to improve readability. It also adds the following options to `aur-build`:
* `-R`, corresponds to `repo-add -R` (partially related to #305)
* `-v`, corresponds to `repo-add -v`. This was priorly part of `aur-build -s`.
The short option `-n` was also removed from `aur-sync`, as it might be confused with `repo-add -n`. The long `--noconfirm` option to `makepkg` and `pacman` was kept.
=> Add aurbuild -R, -v

man1/aur-build-nspawn.1, man1/aur-build.1, man1/aur-deps-rpc.1, man1/aur-deps-src.1, man1/aur-fetch.1, man1/aur-pkglist.1, man1/aur-rfilter.1, man1/aur-rpc.1, man1/aur-search.1, man1/aur-srcver.1, man1/aur-sync.1, man1/aur-vercmp.1, man1/aur.1
While reading the man pages *a lot* yesterday, it bothered me that usage of bold and italics was rather inconsistent. This PR aims to:
- Unify bold and italic usage
- Repeat option arguments in the OPTIONS sections
And while working on those, I noticed that a couple (read: many) hyphens needed escapation, because otherwise they become subject to line wrapping.
The only non-formatting changes were changing one "workarounds" to "works around" and changing a "suffix" to "prefix", both in aur-sync(1).
=> man formatting

lib/aur-search
Inspired by yay 🙂
I realized what I'm missing from yay - indicators "orphaned" and "out-of-date". I don't think any configuration options are needed to disable this behavior.
=> aur-search: Add indicator of orphaned and out-of-date packages

man1/aur-build-nspawn.1, man1/aur-build.1, man1/aur-deps-rpc.1, man1/aur-deps-src.1, man1/aur-fetch.1, man1/aur-pkglist.1, man1/aur-rfilter.1, man1/aur-search.1, man1/aur-sync.1, man1/aur-vercmp.1
Here are some documentation improvements that I failed to get ready in time to piggyback #322.
Align options with descriptions if there is space for it.
Add some missing section numbers.
Add mention that sudo wildcarding aur might run aur- prefixed scripts from $PATH
Add some missed escapes for -
Fix inconsistency between manpage formatting of arguments inside square brackets
=> additional documentation fixes (follow-up to #322)

lib/aur-search
Just to be done with aur-search bugs 🙂
This fix kinda depends on the fact that `(Oprhaned)` is always before `Out Of Date`, not sure if you want something more sophisticated that this...
P.S. I found `-a` useful for showing relevant screenshots, it allows to gather all important cases in one picture 🙂
Fixes #337.
=> Make sure the is no extra space when package is not orphaned

lib/aur-fetch-git
Specifying a relative directory will trigger a regression under some
circumstances.
$ GIT_DIR=spotify/.git GIT_WORK_TREE=spotify git reset HEAD
fatal: couldn't read spotify/.git/packed-refs: Not a directory
$ GIT_DIR=$PWD/spotify/.git GIT_WORK_TREE=$PWD/spotify git reset HEAD
=> specify absolute paths for GIT_DIR & GIT_WORK_TREE

man1/aur-build.1
Added mention to the GPGKEY variable to use another key for signing. This variable doesn't seem to be documented at all.
=> Add documentation for GPGKEY variable

lib/aur-srcver, makepkg/PKGBUILD
How it works:
1. `--halt soon,fail=1` is **not used**, I want to update as many packages as possible, if one keeps failing it shouldn't block the rest
2. `--results '{#}_makepkg'` saves stdout and stderr of every makepkg run, `{#}` is the sequence number, used later to determine which run failed
3. `--joblog makepkg_log` saves the `tsv` table of which command finished and which failed, in there I can see a command, its exit code and its sequence number.
`parallel` exits with a code that corresponds to the number of jobs that failed. If any job failed, look in `makepkg_log` which jobs failed, find corresponding stdout and stderr files using the sequence number and print all of this to stderr.
In the end, print out the latest known versions. Even if one or two updates failed, the rest have …
=> Use parallel to speed up aur-srcver

lib/aur-sync, man1/aur-sync.1
For when you want the latest commit of *everything*.
=>  aur-sync: Allow reading package names from standard input 

contrib/README.md, contrib/aur-vercmp-devel
I realized that I would actually benefit more from having a script that _detects_ outdated VCS packages, and extracted it into `aur-vercmp-devel`. The `aur-update-devel` becomes a one-liner, I still find it useful, but I'm not sure if you are OK with keeping it in the contrib 🙂
=> contrib: Extract aur-vercmp-devel

lib/aur-srcver
Simple way to fix #380: print a message and exit if parallel exit code is >101.
Also adds a special check if `parallel` is not available, because it is a required tool and we want to be as clear about this as possible.
```
❯ lib/aur-srcver ~/.cache/aurutils/sync/*-git
srcver: "parallel" is not found in $PATH
```
=> aur-srcver: Handle errors with running parallel

lib/aur-graph
Sparsity checks were removed for performance reasons. (`gawk --profile`)
Solves #10. After 2 years! :tada:
=> aur-graph: support versioned dependencies

lib/aur-depends, lib/aur-fetch, lib/aur-sync, man1/aur-depends.1
To better reflect the name (and more generally, to reduce the scope of the tool), this
commit removes most processing of the retrieved dependency information from the AUR.
In particular, if a total order is required, this must be done manually through cut(1)
and tsort(1).
Usage in aur-fetch remains similar, apart that pkgbase must be used when retrieving
build files (this was an oversight when recursion was introduced with commit
3bd2fcbcacdb939cbc782a99702580db35cdc24b).
Adapting aur-sync(1) is a more challenging task, and is not fully covered by this
commit.
=> aur-depends: remove unrelated functionality

lib/aur-sync
- Exclude `.` from results of `find` (screenshots below)
- Specify `.` as the first argument for `find`, because shellcheck says not all implementations of `find` default to the current directory.
--------------
`find -maxdepth 2 | vifm - '+view!'`
`find -maxdepth 2 -mindepth 1 | vifm - '+view!'`
=> aur-sync: exclude $tmpview itself from `find` results

lib/aur-search
Votes are now prefixed with + and popularity is suffixed with %.
I tend to prefer this format as it clearly shows which number is which.
=> aur-search: Show popularity and tweak formatting

man1/aur-build.1
I've been debugging an issue on some of my systems where `aursync` was still prompting for passwords when I was aiming for a hands-off build after reviewing AUR diffs. It turns out that specifying `localhost` in a `sudoers` config line _only_ applies in cases where the host's canonical hostname is actually "localhost". Here's a quote from `man sudoers`:
> Note that sudo only inspects actual network interfaces; this means that IP address 127.0.0.1 (localhost) will never match.  Also, the host name “localhost” will only match if that is the actual host name, which is usually only the case for non-networked systems.
In the absence of a more specific hostname value that could apply generally in the man pages, `ALL` seems like the next-best thing. It casts a wider net than (what we'd like to …
=> aur-build: Update sudoers docs to not use localhost

lib/aur-build, lib/aur-chroot, lib/aur-fetch, lib/aur-fetch-git, lib/aur-fetch-snapshot, lib/aur-pkglist, lib/aur-repo-filter, lib/aur-rpc, lib/aur-search, lib/aur-sync, lib/aur-vercmp
Pacman 5.1 provides a util script for option parsing that supports short
and long options.
In addition to provide easier to read options, this will also benefit
completion scripts that rely on parsing the output of `--help`.
--- 8< ---
I didn't have time to test this today, but wanted to put this out so we can have a dedicated place to discuss this.
134264b just converts existing use of `getopts` to `parseopts` without adding any extra functionality. Thus, `aur-{srcver,jobs,graph,depends}`<sup>1</sup> scripts remain without long option support.
I tried to follow the loop style used upstream where it uses a common `shift` for all options and the same line for the `pattern)` and `list ;;`. Saves a bunch of vertical space which makes it a bit nicer to read. But long `patterns)` kind mess up …
=> scripts: use util/parseopts.sh for option parsing

man1/aur-vercmp.1
I saw the `[-p path]` in the man page but it was never explained. Hopefully I got its usage right.
=> Document -p for aur ver-cmp

lib/aur-chroot
Closes #426. I added `env` inside `sudo` because that's what makechrootpkg does, not sure if it’s necessary.
=> Preserve GNUPGHOME in aur-chroot

man1/aur-repo-filter.1
There are some differences in the documentation and the actual behavior of `aur repo-filter`.
=> Update man of aur repo-filter

lib/aur-repo-filter
If --repo=reponame is not passed to pacsift, then it won't filter to match
$reposet and will output 'local/pkgname' which then yields an expac
'package not found' error.
=> aur-repo-filter: pass --repo=... to pacsift

man1/aur.1
Print Perl modules that are both in the AUR and official repositories:
=> using -v will show Perl modules that are in official repositories but
not in AUR
Check foreign packages for AUR updates:
=> without -m then this checks all packages
=> aur.1: fix typos

lib/aur-build, lib/aur-sync, man1/aur-build.1, man1/aur-sync.1
This allows to specify the root via an env var rather than the -r argument.
=> Add $AUR_DBROOT

lib/aur-chroot
`aur sync -c -d foo -r foo_db_path` will call `aur chroot -d foo`, and
if the repo 'foo' does not have a corresponding 'file://' entry in
pacman.conf, then the grep -Em1 fails which exit the script.
But this is not an error, it just means that the corresponding directory
won't be bind_mounted. So desactivate 'errexit' for this case.
=> aur-chroot: A local repo without a file:// entry is not an error

completions/Makefile, completions/bash/aurutils.in, completions/command_opts.m4, lib/aur-build, lib/aur-chroot, lib/aur-fetch, lib/aur-fetch-git, lib/aur-fetch-snapshot, lib/aur-pkglist, lib/aur-repo, lib/aur-repo-filter, lib/aur-rpc, lib/aur-search, lib/aur-sync, lib/aur-vercmp
This is still in a very early state. Just opening the PR in order to get some feedback and/or help. 😊 
~~The main idea here is to get autocompletion from the output of `-h` pages. So as long as the help pages get updated, completions for short and long options come for free.~~
~~While this is convenient, in some cases we might want to define completions for other things, e.g repos for `-d` option etc. This will provide completions based of `-h` flags unless there's a function defining how the command should complete.~~ (moving away from parsing help text. see: https://github.com/AladW/aurutils/pull/311#issuecomment-401462680).
Stuff to consider
=> preliminary bash completion

lib/aur-repo
Fix a copy&paste error introduced in d6881cb3e3ce0152c1f7f788ca79ba64efc1cae6. This is necessary for `aur repo -u` and `aur repo -S` to work correctly.
=> aur-repo: fix sync_format

Makefile, completions/Makefile, completions/command_opts.m4
* fix multiple issues related to completion generation. Some caused by issues on the completions/Makefile and another caused by the m4 macro itself. Both could result in installation of stale completion scripts.
* Add vercmp-devel to completion macro
* Install bash completion by default
=>  Install bash completion by default

lib/aur-chroot
The line from get_conf_repo is in format `Server = file:///path/to/repo`. Without successful bind mount, `pacman -Syu` fails in prepare stage, stopping the build.
=> aur-chroot: fix local repo path for bind mounts

man1/aur-build.1
`aur build`'s man page is inconsistent with its actual behaviour; options are passed to `makechrootpkg` and not `aur chroot` itself.
I also added a short note about `-C`, `-D` and `-M` options, as these aren't mentioned anywhere else in `aur-build(1)`.
=> aur-build: Fix documentation inconsistencies

lib/aur-search
`aur-search` only prints colors on stdout.
=> aur-search: colorize if stdout is a tty

lib/aur-repo
`aur repo --repo-list` prints non-error output to stderr instead of stdout
=> Change aur-repo --repo-list to print to stdout

lib/aur-build
This used to work in the past, but was lost at some point during the refactoring.
Personally, I use one local repo `aur` for packages built directly from the AUR without modifications, and one repo `custom` which holds modified and self-created packages. As most of the dependencies will land in the `aur` repo, it is almost always required during `aur build`.
=> aur-build: Allow passing multiple local repos to aur-chroot

lib/aur-repo, man1/aur-repo.1
Because repository names cannot contain newlines, pacsift --null is not
required and the output can be parsed line-by-line. For a simple command
line, expac is used instead of pacman --print.
Add a sync "modifier" that applies to both package listing and package
upgrades. It is disabled by default; in particular, aur repo -u is now
equivalent to "aur repo -l | aur vercmp". If the repository path is
remote, hint to -S which enables it.
-Sl and -l have the same output: pkgname and pkgver separated by tabs.
=> aur-repo: simplify pacman query, add -S

lib/aur-repo, man1/aur-repo.1
Fix two bugs introduced in #491:
- `aur repo -Sl` fails with the error
```
awk: cmd. line:2:         $0 ~ rname { print $NF }
awk: cmd. line:2:                    ^ syntax error
```
due to a spurious pair of braces in the AWK program used by `ex_namever`.
- `aur repo -u` only returns the path to the database file due to a typo (`list_updates` instead of `list_upgrades`). Additionally correct the name of the long option name in the man page from `--updates` to the actually used `--upgrades`.
=> aur-repo: fix --sync and --upgrades

completions/Makefile, completions/zsh/README.run-help-aur, completions/zsh/run-help-aur
run-help-aur is a Zsh run-help assistant. It allows `run-help` to open the correct man page for `aur *` commands, instead of opening `aur(1)`.
To use it, first setup `run-help`, then place `run-help-aur` in `fpath` and autoload it. For example, with `run-help-aur` in `/usr/share/zsh/functions/Misc/run-help-aur`:
```
unalias run-help
autoload -Uz run-help
autoload -Uz run-help-aur
```
After that invoke `run-help` on a `aur *` command and it will open the correct man page. E.g.: `run-help aur sync` will open `aur-sync(1)` and `run-help aur build` will open `aur-build(1)`.
`run-help` and its assistant functions are documented in `zshcontrib(1)`.
=> Add zsh run-help assistant

lib/aur-sync
Previous versions of aur-sync used to set the current directory to the per-sync temporary directory before invoking the `$PAGER` command. Recent changes (65517a01fdcad12e4cb75ce05d636d8571dc0e21) broke this assumption. (This was broken for both `$PAGER` and vifm, but was later fixed, only for vifm, in 854c85ee0612ff5ca0ab982e41dd5126b07a8df6).
=> lib/aur-sync: cd before invoking $PAGER again

lib/aur-sync
aur-build has the option to delete old package versions via -R. This commit enables the option for aur-sync also and fixes the bug that the -r option was not recognized.
=> Add -R (and enable -r) option to aur-sync

completions/bash/aurutils.in, completions/command_opts.m4, completions/zsh/aurutils.in
Completions options are being shown in lexicographical order. The result
is that long and short options are shown mixed up.
This makes the completions hard to read as they're not well aligned due
to prefix length differences between short and long options (--/-).
To minimize these misalignments lets show them grouped together, showing
long options first followed by short options.
In response to #514
=> completions: group options by type

lib/aur-srcver
This removes the `readlink`/`find` hacks from `aur-srcver`, using exported functions with `parallel` instead.
Note: as before, results are only printed if all arguments were processed successfully. Not sure if this is the best approach; I only vaguely recall discussing it.
=> aur-srcver: use exported functions

completions/command_opts.m4, lib/aur-srcver, man1/aur-srcver.1
d2c26cc removed the `--noprepare` flag from `makepkg` calls in `aur srcver`. 
This made calls to `aur-srcver-devel` slow because in my particular case a go package's `prepare()` was running `dep ensure` which took some time to finish.
If `pkgver()` is allowed to depend on the result of `prepare()` maybe this is wrong and is something we'll need to live with?
=> srcver: re-add --noprepare

completions/command_opts.m4
In cadf3f7 (aur-depends: implement --pkgbase, --pkgname, --table,
2019-01-14) aur depends gained option handling but completion for it is
not being generated.
I noticed that there was a mismatch in number of scripts using parseopts
and the number of scripts with autocomplete, but because the macro
arguments were not lexicographically sorted spotting the missing one
took more seconds than it should.
So lets sort the arguments and move depends to HAVE_OPTDUMP so
completions are generated for it.
=> completion: generate completion for aur-depends

lib/aur-build, lib/aur-chroot, lib/aur-depends, lib/aur-fetch, lib/aur-pkglist, lib/aur-repo, lib/aur-repo-filter, lib/aur-rpc, lib/aur-search, lib/aur-srcver, lib/aur-sync, lib/aur-vercmp
opt_hidden is not being unset after option handling in all but one
script. As this seems like an unnecessary step, instead of also
unsetting opt_hidden everywhere let's just stop unsetting those helper
variables.
This was brought up in #aurutils. Is there any real benefits from unsetting those variables here? If not, let's just remove all those lines. If yes, this can be converted into a PR that fixes all the missing `unset opt_hidden`.
=> stop unsetting parseopt helper variables

Makefile, completions/Makefile
I came across this while debugging and trying to install aurutils manually on a `DESTDIR` that happened to contain a space.
=> Makefile: quote variables to prevent wordsplit

lib/aur-sync
`aur sync` will use $PAGER if `vifm` is not avaiable, falling back to
`less -K` if $PAGER is unset. `aur sync` uses the exit code from this
invocation to decide if the build process should continue or should be
aborted. This is a important part of the process as continuing implies
the user reviewed and agreed to run the PKGBUILD.
While vifm and the current default (less -K) allows exiting with error
by using :cq or ^C respectively, if the user has $PAGER set to something
that doesn't wait for user input and provide a way to exit with error,
or has LESS=F which causes `less` to exit successfully if the output
fits in one page, aur sync will proceed without explicitly consent from
the user.
Let's override the -F option on our default fallback making sure it
always paginate, and prompt for …
=> sync: ask for confirmation when using PAGER

lib/aur-build, man1/aur-build.1
Building deltas is a _time hog_, and deltas are pretty much never used in a small network environment.
It would be nice to have this feature turned off by default, and only activated with a flag. 
_can't reopen  #528, after force push :disappointed:_
=> aur-build: make repo-add -d optional

Makefile
To facilitate the customization of the aur wrapper, allow overriding the
lib_dir that becomes hardcoded in `aur`.
This can be useful in situations where the user wants to have multiple
installs running from different lib_dir's. While you can, this should
not be used to bypass the limitation that you cannot override default
scripts using aur-scripts in your $PATH.
If you do it, do it at your own risk.
=> aur: allow overriding aur lib_dir at build time.

aur.in
The aur wrapper prepends $lib_dir to $PATH to ensure it is using its own
scripts. But due to the modular nature of aurutils the wrapper is called
multiple times throughout multiple pipelines causing multiple instances
of $lib_dir being added to $PATH.
Only prepend $lib_dir to $PATH if it isn't the first occurrence.
=> aur: Don't add lib_dir to PATH if already there

lib/aur-sync, man1/aur-sync.1
Merge input from `--ignore-file` and `--ignore` regardless of location on
the command-line. In particular:
```
$ aur sync --ignore a,b,c --ignore-file d
```
now ignores both `a,b,c` and packages in `d`. The default `--ignore-file` is
set to `$XDG_CONFIG_HOME/aurutils/sync/ignore`.
=> aur-sync: add default --ignore-file location

lib/aur-repo
This has two benefits:
1. Consistent with `aur-repo` when invoked without arguments, which only lists a path.
2. Makes looping over the output easier, i.e. does not require `cut`.
The repository name is simply the database name without `.db` extension, and can be retrieved with `basename`:
```
aur repo --repo-list | while read -r; do
name=$(basename "$REPLY" .db)
done
```
=> aur-repo: --repo-list: use full paths instead of tsv output

man1/aur.1
This PR adds examples of `aur` user scripts, in particular `aur-gc` (#317) and `aur-remove` (#305), as well as a reference to the `AUR_LIB_DIR` macro. 
`aur-remove` assumes that `aur-repo --repo-list` outputs a list of paths (see #539), but this could be changed as required.
Closes #217
=> aur.1: add custom commands

lib/aur-chroot, man1/aur-chroot.1
PR #544 added `--config` to `host_with_cache`, it however used the same
pacman config as used in the chroot. In particular, `CacheDir` and
local repositories on the host would not be added.
Besides some stylistic changes, this PR also fixes the long options
which were missing an argument.
=> aur-chroot: add --host-conf

lib/aur-fetch, lib/aur-sync, makepkg/PKGBUILD, man1/aur-repo.1, man1/aur-sync.1
This is based on a `sh` rewrite by @Earnestly of #525, in particular https://github.com/AladW/aurutils/pull/525#issuecomment-471142788. The version in this PR mainly adds some boilerplate for completions. The changes to the current `aur-fetch` are:
* Remove tar support. It was originally added due to git pull being slow on high workloads, but since using `parallel` in `aur-sync` the difference is small.
* Add `--verbose` and `--write-log` to print diffs to stdout and to `.patch` files in a directory, respectively. Both options may be combined.
* Save the git orderfile for all cloned `git` repositories in `$XDG_CONFIG_HOME/aurutils/fetch`.
The man page is not yet complete and should include a description on how diffs are generated and resets are done.
=> aur-fetch: remove --tar support

lib/aur-repo, lib/aur-repo-filter, makepkg/PKGBUILD, man1/aur-repo-filter.1
* **aur-repo-filter**
+ Recent versions of `pacinfo` have an easy to parse, line-by-line format, removing the need for `expac`. Newline seperation should suffice, so remove `--null`.
* **aur-repo**
+ Using `DBPath` allows to run `db_namever` on the sync db for a given repository.
The man page of `aur-repo-filter` should likely be updated to mention why #542 could not be implemented.
=> Remove expac dependency

lib/aur-fetch
The AUR enforces a ff-only policy for PKBUILDS, however, in rare
occasions TUs will rewrite and force-push. Prime exemple being removal
of commits that introduce malicious code to the package.
Refuse to fetch in such scenario. When this happens, the user should
investigate why history got rewritten and take appropriate measures.
The check can be bypassed by the new option `--force`.
Users should update any existing cached repos to make sure they have the
non-fastforward refspec:
find "${AURDEST}" -name .git -execdir git config remote.origin.fetch 'refs/heads/*:refs/remotes/origin/*' \;
=> aur fetch: fail if history was rewritten.

lib/aur-sync
aurutils should trust `vifm` exit codes as a signal that build files
were reviewed. But (532), the fix for (530), does not properly handle
all use cases. In particular, it asks for confirmation after review in
`vifm` if PAGER is set, when PAGER wasn't used in the first place.
Fix that.
=> Do not prompt after vifm review when PAGER is set

lib/aur-build, lib/aur-depends, lib/aur-fetch, lib/aur-repo, lib/aur-repo-filter, lib/aur-search, lib/aur-srcver, lib/aur-sync, lib/aur-vercmp, man1/aur.1
When color options are not specified, color ouput unless stdout or
stderr is not connected to a terminal.
With --color and --no-color, the colorization can be forced on or off.
=> scripts: respect environment variable AUR_COLOR

man1/aur-depends.1, man1/aur-fetch.1, man1/aur-repo.1, man1/aur-search.1, man1/aur-sync.1, man1/aur-vercmp-devel.1, man1/aur-vercmp.1
A couple of documentation fixes. 
Quick summary:
- Removes references related to `aur fetch --tar`
- Adds missing documentation of `aur fetch --force`
- Updates the documentation of `aur repo --repo-list`
- Fixes to things that were missing or not being correctly rendered
=> manpages fixes

lib/aur-chroot, lib/aur-pkglist, lib/aur-rpc
Some of the scripts failed to receive the #557 treatment,
9dba6dd (scripts: respect environment variable AUR_COLOR, 2019-04-15).
Correct that.
=> scripts: respect environment variable AUR_COLOR, part 2

lib/aur-fetch, lib/aur-sync, man1/aur-fetch.1
On bc8d5c8 (fetch-git: discard local changes ... 2018-04-12)
aurutils took a holistic approach when it comes to allowing users
modifying files inside cached repos. Discarding any changes when a
package is to be updated.
This obviously isn't very practical, as some packages require
adjustments because they're either broken or the user wants to tune a
particular aspect of it.
Another concern was that automating non-fast-forward merges could end up
keeping commits that TU wrote out of history. But that being addressed
by ad8723d (fetch: refuse to fetch non-fast-forward refs, 2019-03-18),
allow us take a different approach:
Discard any uncommitted changes but reapply any local commits on top of
the incoming changes.
Only local user commits have the potential to generate conflicts when …
=>  fetch: preserve committed modifications to package 

lib/aur-fetch
`gen_patchfile` is defined in PR-565 and was used here by mistake.
Correct that by reverting to the explict git call.
=> fetch: remove use of undefined function gen_patchfile

man1/aur.1
The aur-remove script suggested in `aur(1)` has a bug that results in
data loss:
If the user runs the script without arguments, package=$1 will be empty,
which results in -name "$package*" expanding to -name "*" deleting all
packages and the database itself.
If the user has packages that share the same prefix, e.g. aurutils and
aurutils-git, aur remove aurutils will remove aurutils from the db but
delete aurutils and aurutils-git packages from disk.
Refactor the script using `paccache` from `[community]`.
Closes: #570 
Helped-by: Earnestly
=> man1: Improve suggested remove script

lib/aur-repo
fc4fc06 (aur-repo: remove expac, 2019-03-14) breaks --sync by
incorrectly determining pacman_dbpath.
Fix that.
=> aur-repo: fix --sync option

lib/aur-fetch
Review patches are not being generated on first clone. Fix that.
If --confirm-seen is used on first clone cases, it is assumed the user
trusts the source and the patch generation is skipped.
Hint: Easier to review if whitespace changes are hidden
https://github.com/AladW/aurutils/pull/586/files?w=1
=> aur-fetch: Generate full patch on first clone

lib/aur-srcver, man1/aur-srcver.1
See #582. This commit also adds the `-j`/`--jobs` flag for the upper bound of makepkg jobs.
=> aur-srcver: remove parallel

lib/aur-sync, man1/aur-sync.1
This allows adding reason(s) why a specific package was put on ignore.
=> aur-sync: allow to add comments to ignore-file

lib/aur-build, lib/aur-depends, lib/aur-fetch, lib/aur-pkglist, lib/aur-query, lib/aur-repo, lib/aur-repo-filter, lib/aur-search, lib/aur-srcver, lib/aur-sync, lib/aur-vercmp, man1/aur.1
This commit replaces `AUR_COLOR` with `NO_COLOR`, effectively removing `AUR_COLOR=always`. `aur-search` is now colorized unconditionally, leaving disabling colors to the user.
For simplicity, colors are removed from the plumbing commands as well.
Fixes #585
----
Taken from https://github.com/rafasc/aurutils/commit/4c8222fe2f487f696f751608954b6ff1906896ac
=> implement NO_COLOR

man1/aur.1
The example `xargs -a installed.txt aur sync --repo=custom` should be `xargs -a installed.txt aur sync -d custom`.
=> Update xargs example in aur.1

man1/aur-build.1, man1/aur.1
Databases over 25M may result in "expected download size exceeded"
errors on pacman -Syu. Document this limitation, and change the example
on creating a new repository to enable gz compression.
Fixes #594
=> man1: document pacman db size limits

lib/aur-repo, man1/aur-repo.1
aur-repo: add --table
PR #581 was rejected in favor of documentation. In its implementation a `--table` feature was discussed/added. This PR is the cherry-pick of the commit that implemented `--table` so we can merge this independently of `--devel` from #581
=> aur-repo: add --table

lib/aur-build, lib/aur-sync
`makepkg` does not support `--asroot` since pacman 4.2, and extra care should be taken when trying to run it as root (such as dropping privileges). Add a mollyguard to prevent this from accidentally happening, e.g. through `sudo aur sync`.
Since the behavior is self-explanatory and not required for normal operation, I did not document the variable in `aur-build(1)` or `aur-sync(1)`.
=> add mollyguard for aur-build/aur-sync

Makefile, lib/aur-srcver, lib/aur-sync
Only ignore unsuported languages (SC1071)
Hide false positives on a case by case basis
=> shellcheck: minimize exclusions

lib/aur-srcver
`--log` was added as workaround when `makepkg` output went "missing" while using `parallel`. Since we no longer use parallel (and `--log` apparently stacks the logs, potentially resulting in dozens of log files), remove the option again.
=> aur-srcver: remove makepkg --log

lib/aur-build, lib/aur-depends, lib/aur-fetch, lib/aur-pkglist, lib/aur-query, lib/aur-repo, lib/aur-repo-filter, lib/aur-search, lib/aur-srcver, lib/aur-sync, lib/aur-vercmp, man1/aur.1, man7/aurvcs.7
Some programs rely on setting `PS4` to a different value. As `readonly` variables in general have had no effect in `aurutils` over the course of its existence, let's remove them wholesale.
Fixes #524
=> scripts: remove readonly variable assignments

README.md
As building AUR packages is the user's responsibility, so is rebuilding them for example on `soname` changes in official repository packages. Add a hint in the `README` for a project which helps with this task.
Fixes #612
=> README: add rebuild-detector

lib/aur-sync, man1/aur-sync.1
Change `--provides` to take any `pacman` sync repository into account, as this case is more common than the "self-sufficient" case where only virtual dependencies in the local repository are considered.
To preserve and extend the latter approach, add a new option `--provides-from`. This option can be seen as a special version of `--provides`, and is checked for first in the `aur-repo-filter` block.
=> aur-sync: add --provides-from, change --provides

NEWS.md, makepkg/PKGBUILD, makepkg/aurutils.changelog
This allows viewing release changes with:
```
$ pacman -Qc aurutils-git
```
The only required change is the newline at the end of the file; see `PKGBUILD(5)`. As the changelog uses markdown, it can be viewed in `html` as follows:
```
$ pacman -Qc aurutils-git | md2html | lynx -stdin
```
where `md2html` is part of the `md4c` package.
Fixes #624
=> move NEWS.md to aurutils.changelog

lib/aur-fetch, man1/aur-fetch.1
AUR_SEEN is becoming the standard ref name, yay and pacaur also support
this.
=> Use AUR_SEEN instead of AURUTILS_SEEN

lib/aur-build, lib/aur-fetch, man1/aur-fetch.1
Implements:
* ability to choose between git reset (default)/pull --rebase to update cached repos. (discard local commits vs trying to reapply local commits on top of the incoming changes)
from #634. Additionally adds a `--results` flag to allow for separation of "new" and "existing" packages in `aur-sync`, see #379.
=> aur-fetch: add --rebase, --results

test/issue-636
Using `master` at 1b4782e2e10acb807c87d81b03f1d9b583bb9d4, `aur-fetch` exits with nonzero status under the following conditions:
1. It needs to fetch more than one repository
2. At least one repository (other than the first one listed on the command line) is being fetched for the first time (initial `git clone`):
```
$ cd "$(mktemp -d)"
$ aur fetch aurutils aurutils-git 
Cloning into 'aurutils'...                                         
remote: Enumerating objects: 348, done.                            
remote: Counting objects: 100% (348/348), done.                    
remote: Compressing objects: 100% (232/232), done.                 
remote: Total 348 (delta 117), reused 347 (delta 116)              
Receiving objects: 100% (348/348), 66.21 KiB | 622.00 KiB/s, done. 
Resolving deltas: …
```
=> aur-fetch: unset GIT_DIR and GIT_WORK_TREE

lib/aur-build, lib/aur-repo, lib/aur-repo-filter, lib/aur-sync
Add the `--path` command-line option to print paths, and exit with `usage` if not specified. This way, the user must explicitely specify the operation they want to perform (issue #555).
Change `--repo-list` to only print the names of `file://` repositories, for easy processing where only these names are required (e.g. `aur-build -d` or `aur-sync -d`). The previous behavior, where paths are printed in full, can be achieved by combining `--repo-list` with `--path`.
----
In summary, we have the following options:
1. `aur repo --repo-list`
-> Print `file://` repository names
2. `aur repo --repo-list --path`
-> Print paths of all `file://` repositories
3. `aur repo --path`
-> Print path of single `file://` repository
4. `aur-repo`
-> Print usage text
----
Closes #555
=> aur-repo: add --path

lib/aur-build
This was done after some concern that `PKGDEST` may be used by other programs (in particular, build systems) besides `makepkg`. However, the variable is defined in `makepkg(8)` as being possible part of the environment, and the custom `makepkg.conf` parser has broken before (i.e.
a newline was missing in the last concatenated `makepkg.conf` file).
As this problematic mostly arised due to `yaourt` exporting every variable in `makepkg.conf` (`BUILDDIR` included), restore the original behavior. See also:
https://wiki.archlinux.org/index.php?title=Talk:AUR_helpers&oldid=590741#Drop_%22Clean_Build%22_Column
=> aur-build: pass PKGDEST directly to makepkg

lib/aur-build, lib/aur-fetch, lib/aur-query, lib/aur-repo-filter, lib/aur-search, lib/aur-sync, man1/aur-build.1, man1/aur-sync.1
Traditionally, `aur-build` has a set of default (`makepkg`, `makechrootpkg`) options that can be overridden by a new set of options, specified after `--`. This means adding a simple option like `-r` is done as follows:
```
$ aur build -- -r -sc
```
where `-sc` are the default `aur-build` options (here, we've replaced `makepkg -sc` with `makepkg -src` in the `aur-build` invocation). A possible option is to append to the default options, instead of overwrite them:
```
$ aur build -- -r
```
In this case `aur-build` contains a set of `hardcoded` options which may not be suitable to all users.
This commit removes any notion of default arguments for `makepkg` or other wrapped build commands. For convenience, common options are parsed directly from the command-line, including `makechrootpkg` …
=> aur-build: remove default arguments

lib/aur-fetch, lib/aur-sync
Make `aur-fetch` non-destructive by default, to either update AUR_SEEN (if `--confirm-seen` is specified) or run `git-fetch -v`. 
If `--sync=reset` or `--sync=rebase` are specified, `git reset --hard HEAD@{upstream}`, and `git reset --HARD; git merge` are run, respectively. 
`sync=auto` decides the action based on the `aurutils.rebase` configuration setting, defaulting to `--reset`, and this option is used by `aur-sync`.
----
As usual, documentation updates are missing.
=> aur-fetch: add --sync

lib/aur-build, lib/aur-sync
Rebases @Foxboron's PR #614 on master.
* [aur-build] Ensure we propegate pacman.conf to aur-repo when finding
the repository we build against.
* [aur-build] Renamed p_conf to pacman_conf for internal consistency
* [aur-sync] Ensure pacman.conf is propegated to aur-repo when we find
the build repo.
=> Ensure aur-repo always gets the pacman config

lib/aur-build, lib/aur-fetch, lib/aur-repo-filter, lib/aur-search, lib/aur-sync, lib/aur-vercmp
`msg`/`msg2` using `stdout` breaks the version output in `aur-sync`, and there is otherwise no reason to use these functions for non-stderr output.
=> scripts: fix use of msg/msg2

completions/command_opts.sh, lib/aur-build, lib/aur-chroot, lib/aur-sync
This is a compromise between the previous `aur-chroot` and a full delegation to `archbuild`. In particular, a dedicated `pacman.conf` is used for the chroot (defaulting to `/usr/share/devtools/pacman-extra.conf`, with `extra` as a configurable prefix) with no additional processing.
`aur-chroot` differs as follows from `archbuild`:
* `Include` directives are supported;
* `makechrootpkg` arguments can be overridden from the command line;
* the distinction between `multilib-devel` and `base-devel` is derived from the supplied prefix instead of `$0`;
* the `arch-nspawn`, `mkarchroot` and `makechrootpkg` steps can be used seperately;
* both `makepkg.conf` and `pacman.conf` can be specified from the command-line.
=> scripts: readd aur-chroot

lib/aur-build, lib/aur-chroot
Follow-up to https://github.com/AladW/aurutils/pull/655
Some typos fixed.
Most controversial question: as you can see I removed `--create` because I dont really see the need for it, aurutils is perfectly capable to figure out on its own if it needs to initialize chroot before building. Am I missing something?
This works when both `/var/lib/aurbuild` doesnt exist and when it is already initialized.
=> Fix building in chroot

lib/aur-build, lib/aur-chroot
I don't understand the purpose of `--create` and how it's intended to be used, I think `aur-chroot` can perfectly well understand when chroot needs to be initialized, so let's not even ask user to do so?
=> aur-chroot: create automatically when necessary

lib/aur-sync
To help with review we call vifm with some commands via -c.
Depending on what the user has vifminfo set to, those changes may be
made persistent between sessions.
Since some of the options are only enabled for the specific usecase of
reviewing pkgbuilds, and to avoid cloberring the userstate, unset
vifminfo to prevent these changes from being written to the vifminfo
file.
---
This was something we found out when playing with `vifm`'s `millerview` and forgot about it.
=> sync: do not save state information in vifminfo

.github/workflows/ci.yml, lib/aur-build, lib/aur-chroot, lib/aur-depends, lib/aur-fetch, lib/aur-pkglist, lib/aur-query, lib/aur-repo, lib/aur-repo-filter, lib/aur-search, lib/aur-srcver, lib/aur-sync, lib/aur-vercmp, test/parseopt-consistency
I'm willing to merge a PR that adds the `parseopt-consistency` test.
_Originally posted by @AladW in https://github.com/AladW/aurutils/pull/667#issuecomment-577803145_
I also included a small github action that runs it automatically on pushes and pull requests.
For now, only the parseopt check is done.
Later, we can include other tests and the shellcheck run. I left it out of this PR because I still didn't investigate how to cache/reuse the expensive `pacman -Syu`.
Or I can drop the actions commit for a later PR.
=> Run shellcheck and option parsing check on pushes and pull requests

Makefile, aur.in, man1/aur.1
Defaults to `AURUTILS_LIB_DIR`, which is defined in the Makefile. The variable name is inspired by `GIT_EXEC_PATH`.
Fixes #645
=> aur: respect AUR_EXEC_PATH

man1/aur-fetch.1
The man page and the actual checked Git config had the section and key switched
=> Fix aurutils.rebase documentation

lib/aur-fetch
There is a fix for this as part of #659, but the discussion on that has been happening for a month, and (at least as a newcomer to the project) it doesn’t look like it’ll be ready to merge soon. In the meantime, #636 is still broken, and it’s only a one-line fix.
=> Fix aur-fetch of more than one package

lib/aur-build, lib/aur-depends, lib/aur-query, lib/aur-search, lib/aur-srcver, lib/aur-sync, lib/aur-vercmp, test/issue-513, test/issue-636
Files created by `mktemp` may have an arbitrary parent directory by setting `TMPDIR`. For example:
```
$ mkdir -p -- -/your/face
$ TMPDIR=-/your/face mktemp -d
-/your/face/tmp.SXrp6oQ7cj
$ rm -rf -/your/face/tmp.SXrp6oQ7cj
rm: invalid option -- '/'
Try 'rm ./-/your/face/tmp.SXrp6oQ7cj' to remove the file '-/your/face/tmp.SXrp6oQ7cj'.
Try 'rm --help' for more information.
```
Avoid this by specifying `--` after each `rm` invocation.
=> scripts: add eof seperator for rm commands

lib/aur-sync, man1/aur-sync.1
This explicitly specifies the packages that ignored for version checks in the option name.
=> aur-sync: --no-ver-shallow -> --no-ver-argv

lib/aur-sync, man1/aur-sync.1
Generalize an additional confirmation prompt for generic viewers set with `AUR_PAGER`, for example for use with GUI file managers without means to exit with status >0 if files were not reviewed or accepted by the user.
Fixes #673
=> aur-sync: add AUR_CONFIRM_PAGER

lib/aur-query, lib/aur-sync, makepkg/PKGBUILD
This removes the dependency on `parallel` besides some other minor tweaks.
Fixes #582
=> aur-sync: remove parallel

lib/aur-sync, man1/aur-sync.1
This is problematic in `aur-sync` as both program names and option names (for `aur-build`) can be placed after `--`. 
See issue #678.
=> aur-sync: remove additional build arguments after --

lib/aur-fetch, lib/aur-sync, man1/aur-fetch.1
A downside of `AUR_SEEN` is that removing the git repositories (e.g the `aur-sync` cache) also removes the reference to the "last seen" revision by the user. This PR removes `AUR_SEEN` from `aur-fetch`, and instead extends `--results` such that higher level tools like `aur-sync` can use their own diff mechanisms which do not rely on git repositories. (I will give the implementation for the latter in a later PR.) 
A side benefit is the reduced complexity in `aur-fetch`, such as absence of the seperate "mode" `--confirm-seen`. The log mechanism is otherwise kept for standalone use of `aur-fetch`.
Also extend `--sync=auto` to only make changes, i.e. run `git-rebase` or `git-reset`, if new upstream revisions are available. Otherwise, perform no action.
=> aur-fetch: remove AUR_SEEN

lib/aur-build, lib/aur-chroot, lib/aur-repo, lib/aur-sync, man1/aur-build.1, man1/aur-chroot.1, man1/aur-repo.1
The main change is this PR is pass on options after `--` to `makepkg` inside the container, instead of `makechrootpkg` on the host. Other changes include re-adding the missing `aur-chroot.1` man page and exposing `--results` to `aur-sync`.
=> aur-build: pass on EOF options to makepkg

lib/aur-pkglist, lib/aur-query, makepkg/PKGBUILD, man1/aur-pkglist.1, man1/aur-query.1
curl can take input from `stdin` through the `-K-` option. Removes the dependency on `wget`.
This affects pretty much all of `aurutils` so there should be no bugs here.
=> scripts: switch to curl

lib/aur-sync, man1/aur-sync.1
Having `aur-sync` ignore providers by default has caused enough confusion over time, let's enable it by default.
Closes #695
=> aur-sync: enable --provides by default

lib/aur-build, man1/aur-build.1
The `prepare` function is run before the `pkgver` function and may thus influence its output.
Remove `--noprepare` from the preparatory `makepkg` command and use `--noextract` for the main makepkg command instead.
=> aur-build: use --noextract for --pkgver build

lib/aur-sync, man1/aur-sync.1
Flag to rebuild a local repository in full or repopulate `AURDEST` in conjunction with `--print`.
Provisions for `--provides` are not required, because `aur-repo-filter` has no output on empty input.
=> aur-sync: add --rebuild-all

lib/aur-build, lib/aur-depends, lib/aur-repo, test/issue-187, test/issue-257, test/issue-403, test/issue-513, test/issue-636, test/issue-706, test/issue-714
aur-repo prints the absolute path to the database as of commit 44ea281d848ef4393a420477c7857531dacde1ee. Strip the extension accordingly if both `$db_name` and `$db_root` are unspecified.
Fixes #714
=> aur-build: strip extension after last .db occurence

THANKS, lib/aur-build, lib/aur-repo-filter, lib/aur-sync, man1/aur-build.1, man1/aur-sync.1
Replace `--build-command` by the following:
1. Add options to the `makepkg` command-line (both on the host and on the container, depending if -c is specified) with the `--margs` option. Arguments are comma-separated and may be specified multiple times. 
To avoid quoting issues with `makepkg --config` through `--margs`, `--makepkg-conf` now sets the makepkg configuration used with `makepkg` for host (non-container) builds.
2. Support the `MAKEPKG` and `PACMAN` environment variables, to set the commands for `pacman` and `makepkg` operations.
Revisit of #678 (@bartoszek) and #709. A test case should include `aur sync --margs -h`.
=> aur-build: add --margs

completions/bash/aurutils.in, completions/zsh/aurutils.in
When we attempt to generate a completion we check if the previous 'word'
matches 'word:' because options which require arguments are marked with
an ':' suffix in the array.
If we find a match, we complete with files by default,
otherwise we show all available options for the subcommand being used.
This worked until aur-repo learned '--repo:'.  Making aur repo <tab>
complete with files, as the subcommand itself matched one of its
options with required arguments.
To prevent that, always complete with options if we are on the second
word.
=> completion: fix broken completion for aur repo

completions/bash/aurutils.in
Specifying a repository is one of the most commonly used options for
anyone who uses multiple repositories.
Let's provide completions for it.
---
Would be nice to keep the zsh completion feature par, but this one is for bash only.
=> bash completion: provide repo completions

lib/aur-build, lib/aur-fetch, lib/aur-sync, man1/aur-fetch.1
Store "seen" git commit hashes (git `HEAD` after `vifm` or `$AUR_PAGER` exited successfully) in the following directory structure:
```
$XDG_DATA_HOME/aurutils/view
|- pkgname1 # <sha_hash1>
|- pkgname2 # <sha_hash2>
|- ...
```
Compared to `AUR_SEEN` (#552) these hashes are stored even if `$AURDEST` is deleted. (#691)
This approach uses `aur fetch --results` to handle all diff functionality in `aur-sync`, instead of relying on `aur-fetch` to generate patches.
Diffs are only displayed if `HEAD` differs from an existing hash. On first run, hashes should be generated for packages in the local repository (#652), for example with:
```
$ aur sync $(aur repo --list | cut -f1) --print
<inspect files and exit with :q when satisfied>
```
----
Possible improvements:
=> aur-sync: store commits reviewed by the user

lib/aur-repo
Follow-up to #729, seems like on an empty DB even though it is not being extracted, the function still doesn't return successfully, and so you cannot build your first package. Having `return 0` is a simple way to ensure the function always succeeds.
=> Make sure db_table exits successfully on empty db

man1/aur-sync.1
I wouldn't add a new repo-add section to the man page like in the aur-build man page, since aur-sync forwards it to aur-build, but it's an repo-add option, so I also could add a new section in the man page.
=> man: add missing --remove option from aur sync

docker/Dockerfile
https://github.com/AladW/aurutils/pull/728/commits/bd261f7ba966854a8b9e0c27dde83300223c4545 changed the Dockerfile to use a single `install` call. 
This prevents using some `aurutils` operations with the unprivileged `archie` user, as `install` seems to only change the ownership of the last path component. 
As a result,  commands like `aur sync aurutils` would fail with:
```
+(/usr/lib/aurutils/aur-sync:213): mkdir -p /home/archie/.local/share/aurutils/view
mkdir: cannot create directory ‘/home/archie/.local/share’: Permission denied
```
=> Docker: /home/archie/.local/ is owned by root

lib/aur-fetch
This was a side-effect of printing the --results output to a file with `tee -a`.
=> aur-fetch: do not print results to stdout

lib/aur-build
This adds a "running" message for all `makepkg` invocations, and removes redundant spaces in their formatting.
=> aur-build: improve "running" messages

lib/aur-repo, lib/aur-sync, man1/aur-repo.1
* Change the verbose output from `--repo-list` to a `pacini`-style format.
* Make the `--status-file` output from `aur-repo` more similar to `--results` from `aur-build` and `aur-fetch`.
For the latter, note that `--status-file` should already be unambiguous: `/` can not appear in `pacman` repository names.
=> aur-repo: improve status file

lib/aur-fetch
https://github.com/AladW/aurutils/commit/d5ec2ddeb1c3a8718adcd0771adce997b8033c57 promised to respect `rebase.autoStash`, however `git reset` would still be run. Read the configuration and only run `git rest` if this option is not set to `true`.
=> aur-fetch: do not reset if rebase.autoStash is set

lib/aur-build, lib/aur-sync, man1/aur-build.1, man1/aur-chroot.1, test/package-tests
Noticed this as my package tests would not use their custom set cache directory: `makepkg -s` runs `pacman` with a few hardcoded arguments; in particular, `--config` is not supported. The only way around this is either use a chroot, or set `PACMAN` to a `pacman --config` wrapper. As former is already possible, this PR implements latter.
=> aur-build: propagate --pacman-conf to makepkg for local builds

lib/aur-build, lib/aur-chroot, man1/aur-chroot.1
Enable functionality with `--update`/`-U` (create or update chroot) and `--build`/`-B` (build package inside chroot), instead of disable it with `--no-prepare` and `--no-build`, respectively.
---
I always found the selective disabling of functionality in `aur-chroot` awkward, and the full program can be enabled by golfing `-UB`.
=> aur-chroot: use --update/--build

lib/aur-build, lib/aur-chroot, man1/aur-build.1, man1/aur-chroot.1
Basic performance comparison on a low-performance VM:
```
[archie@vbox makepkg]$ time makepkg --packagelist
/home/archie/projects/aurutils/makepkg/aurutils-git-3.0.0rc.r7.gc91de35-1-any.pkg.tar.zst
real    0m2.412s
user    0m1.766s
sys     0m0.580s
[archie@vbox makepkg]$ time ../makepkg-fast --packagelist
/home/archie/projects/aurutils/makepkg/aurutils-git-3.0.0rc.r7.gc91de35-1-any.pkg.tar.zst
real    0m0.064s
user    0m0.051s
sys     0m0.008s
```
Where `makepkg-fast` is a script using libmakepkg/util/pkgbuild.sh print_all_package_names() directly if called with --packagelist.
---
A possible issue is that the PKGBUILD is not linted if the build is skipped due to matching version in the local repository. In this specific case, `lint_pkgbuild` could be called (which apparently is a cause …
=> aur-build: use libmakepkg for packagelist

lib/aur-query, man1/aur-query.1
This replaces the `--rpc-ver` and `--rpc-url` options (to allow easy propagation to all utils using `aur-query`), and allows to set the amount of packages before a `GET` request is split to multiple URIs, respectively.
=> aur-query: add AUR_QUERY_RPC, AUR_QUERY_RPC_SPLITNO

lib/aur-build, man1/aur-build.1, man1/aur-chroot.1
This option affects the suffix `extra` in `pacman-extra.conf`, and should thus be called `--suffix`.
=> aur-build, aur-chroot: rename --prefix to --suffix

lib/aur-chroot, lib/aur-sync, makepkg/aurutils.changelog, man1/aur-sync.1
* `aur repo-filter` was run without arguments, limiting the output to the official repositories. Add `--sync` to address this issue.
* `aur chroot` was still using `--prefix`.
=> aur-sync: actually use all provides

lib/aur-repo, man1/aur-repo.1
Instead of having to specify a mode and a modifier for listing packages and repositories, make `--table` and `--ini` two modes. This reduces:
```
$ aur repo --list --table
```
and
```
$ aur repo --repo-list --ini
```
to
```
$ aur repo --table
```
and
```
$ aur repo --ini
```
respectively.
=> aur-repo: simplify command-line

lib/aur-sync
With miller column file managers (in particular, ranger), saving the directory with symlinked build files in `TMPDIR` caused a lot of irrelevant files to appear in the left-most column. Using `XDG_DATA_HOME` allows to use this left-most column to switch to viewed revisions in `XDG_DATA_HOME/aurutils/view`.
To avoid conflicts, the parent process ID is suffixed to the directory name.
Later commits may move this directory (and possibly additional symlinks to directories in `XDG_DATA_HOME/aurutils/view`) to the more suitable `XDG_RUNTIME_DIR`.
Before:
After:
=> aur-sync: use XDG_RUNTIME_DIR for view directory

completions/zsh/aurutils.in
The fix for aur repo completion done in
63641ea (completion: fix broken completion for aur repo, 2020-05-08)
introduced an extraneous newline in the zsh version,
effectively breaking it.
Remove the unwanted newline.
Closes #776
=> Fix broken zsh completion due to unwanted newline

Makefile, lib/aur-build, lib/aur-chroot, lib/aur-sync, man1/aur-build.1, man1/aur-chroot.1
Yet another rewrite of `aur-chroot`... 
* Set the default `pacman.conf` for `aur-build --chroot` to `/etc/aurutils/pacman-<db>.conf`. To accommodate this, the `Makefile` creates `$(PREFIX)/etc/aurutils`. Users will no longer have to write their config in `/usr/share` and can use a `pacman.conf` per local repository with no additional effort (apart from specifying the repository with `-d` or `AUR_REPO`).
* Create containers with `aur chroot --create`, and allow to specify the target packages on the command-line. This way all required packages can be specified in one step, e.g. to include `ccache` in the container. This additional step is only required when using `aur chroot` directly, or if other packages than `base-devel` or `multilib-devel` are required; `aur build` runs `aur chroot …
=> aur-chroot: add --create

lib/aur-chroot
[`multilib-devel`](https://www.archlinux.org/groups/x86_64/multilib-devel/) group is pretty small and does not constitute a usable container. It is intended to be installed on top of regular `base-devel`. Relevant devtools code: https://github.com/archlinux/devtools/blob/20200407/archbuild.in#L7-L14
=> aur-chroot: add base-devel to multilib container

lib/aur-sync, makepkg/aurutils.changelog, man1/aur-sync.1
Allows to take transitive dependencies into account.
Fixes #592
=> aur-sync: add --provides-deep

lib/aur-build, lib/aur-fetch, lib/aur-repo, lib/aur-sync, makepkg/aurutils.changelog, man1/aur-repo.1
1. Fix a bug with `--results` where the results file would be written to $PWD/package instead of $PWD, when using relative paths.
2. Fix #700 by not hardcoding `.db` in `aur-sync`, `aur-build` and `aur-repo`.
3. Add `aur repo --status` for repository selection in `aur-build`. This also generalizes `aur repo --path` (now removed).
=> aur-repo: set repository extension with AUR_DBEXT

man1/aur.1
I'm finding `aur chroot --build` a great helper to check PKGBUILDs. Not finding `aur chroot` in `man 1 aur` threw me off for a bit :)
=> List aur-chroot and aur-query in man1/aur.1

lib/aur-repo-filter, makepkg/PKGBUILD
As of pacman 6, it no longer suffices to close stdin. Use `unbuffer` to simulate a tty instead.
Fixes #804
=> aur-repo-filter: run pacsift with unbuffer(1)

man7/aurvcs.7
=> aurvcs(7): --print was renamed to --no-build

lib/aur-build, lib/aur-sync, man1/aur-build.1, man1/aur-sync.1
There was no real reason to have both flags separated, and `aur-build` does not have a "config" per se. Actually document `--pacman-conf` and `--makepkg-conf` in `aur-sync` as well.
Fixes #808
Fixes #824
=> aur-build: merge --config and --pacman-conf

lib/aur-build
Fixup for b6e2db4d90830686d8d220b939553044dc9573ed
Sorry, I could only actually test that patch today, looks like it was missing a tiny addition.
=> lib/aur-build: Queue existing packages for adding to the repo

lib/aur-build, makepkg/aurutils.changelog, man1/aur-build.1
With #831, `aur-build` detects repository information from the path:
```
/etc/aurutils/pacman-<db_name>.conf
```
However, db_name is not available before this detection takes place. If the
user did not specify db_name, fallback to the path:
```
/etc/aurutils/pacman-<arch>.conf
```
Fixes #846
=> aur-build: fall back to /etc/aurutils/pacman-<arch>.conf

lib/aur-repo
In case a repository package has no dependencies (i.e. the %DEPENDS% pattern is not executed), the `dependencies` variable is not initialized as an array.
The next package will then match `%FILENAME%`, and execute `length(dependencies) > 0` which initializes `dependencies` as a scalar (with value 0).
Avoid this by explicitly defining `dependencies` in BEGIN. Additionally, avoid defining `dependencies` as a scalar in the first place by removing `length(dependencies)`.
If `--table` is set, every package now is listed as depending on itself. This matches the behavior of `aur-graph` and `aur-depends`. Strictly speaking, this is only required for packages with no dependencies, so they appear when piping to `tsort`.
Fixes #813
=> aur-repo: explicitly declare dependencies as array

lib/aur-repo, makepkg/aurutils.changelog, man1/aur-repo.1
Updates `aur-repo(1)` with `--status` and `--status-file`, and removes possible ambiguities between `--repo`, `--repo-list` and `--path` (removed option), `--path-list`
=> aur-repo: remove --path, --repo ambiguities

lib/aur-query
Since curl 7.77.0, exit codes from failed transfers are no longer discarded with `curl --parallel`. Update the code to reflect this.
=> aur-query: remove workaround for curl --parallel exit codes

lib/aur-pkglist
Besides the newly available archives [1], the following has changed:
* aurweb now has Last-Modified and Etag HTTP headers. The refresh time is still roughtly 5 minutes.
* Package archives no longer have a header with the last modified date as a result.
Refactor and add --search, --info for the type=search and type=multiinfo dumps, respectively.
[1] https://lists.archlinux.org/pipermail/aur-general/2021-November/036659.html
=> aur-pkglist: update for new JSON dumps

lib/aur-fetch, makepkg/aurutils.changelog, man1/aur-fetch.1
Possible options to make `aur-fetch` more suitable for non-AUR workflows. Related discussion: #860
=> aur-fetch: add --existing

lib/aur-sync, lib/aur-view, makepkg/aurutils.changelog
#863 
A possible issue is what do with the build order. It is displayed in `aur-view` (as part of the same directory as the symbolic links to package directories), but cannot be modified as a copy. Thus it should either be modifiable, or not shown in the first place. `chmod -w` to emphasize the read-only aspect might be confusing.
A man page for `aur-view` is also missing.
=> aur-sync: move inspection mechanism to aur-view

lib/aur-depends, lib/aur-fetch, lib/aur-query, lib/aur-search, lib/aur-sync, lib/aur-vercmp, makepkg/aurutils.changelog, man1/aur-fetch.1, man1/aur-query.1, man1/aur.1, tests/issue/706
This change allows most `aur` scripts to support both stdin and command-line arguments. In particular, this removes use of `xargs` in `aur-sync` and with that preserves error codes of `aur-depends` and `aur-fetch`. 
Only `aur-fetch` and `aur-query` require explicit support for `-` and `/dev/stdin`. Other scripts call them with their arguments, and so support `-` implicitly.
This PR also removes `--recurse` from `aur-fetch`, because `aur-depends --pkgbase` can now be directly piped into it, as well as stdin "warnings" because the user now has to explicitly request stdin.
=> scripts: support both CLI arguments and stdin

lib/aur-sync, lib/aur-view
Redirecting standard input to aur-view (from a file or elsewhere, using `-`) does the same for any command running inside the script, including file managers set in `AUR_PAGER`.
Most file managers have problems when standard input is not connected to a terminal, e.g. by not displaying files (`nnn`) or aborting immediately (`ranger`). To handle these cases, remove the option to take input from stdin, and add an `--arg-file` option instead, similar to `aur-build`.
Fixes #871
=> aur-view: add --arg-file, remove /dev/stdin

lib/aur-build, lib/aur-sync, man1/aur-build.1, man1/aur-sync.1
Allows to do `aur depends --no-checkdepends` and `makepkg --nocheck` in one step, via `aur sync --no-checkdepends`.
Closes #874
=> aur-build: add --no-check

lib/aur-sync
This is comparable to having the ignored packages in a separate repository.
Also remove the big WARNING for ignored packages; just print them to stderr.
=> aur-sync: apply --ignore to repository targets

man1/aur-build.1
The option has been deprecated and is now just called `auto-key-retrieve`.
>  --keyserver-options {name=value}
> …
>    auto-key-retrieve
>      This is an obsolete alias for the option auto-key-retrieve.  Please do not use it; it will be removed in future versions..
=> aur-build.1: Remove mention of `keyserver-options`

lib/aur-fetch, lib/aur-repo, lib/aur-sync, man1/aur-fetch.1, man1/aur-repo.1
For compatibility with aurutils <3.2.0. All these options (including `--status`) should be considered deprecated and may be modified or removed in any later release.
=> aur-repo: add --path, --path-list, --repo-list compat options

README.md
Move to a single version format (MAJOR) with no specific guarantees on
backwards compatibility.
Closes #888
=> README.md: remove VERSIONING

lib/aur-query
Commit 7c17ad493dc7f19cbd5c4418b79dcbaf46197aed removed the curl exit check, but also removed printing of output files (which were still downloaded). As curl -Z seems to respect output order, simply print to stdout.
Fixes #885
=> aur-query: do not use output files

lib/aur-sync
i.e. the argument to `--ignore-file` can be the result of command substitution (fd). Use `exec` instead.
Closes #880
=> aur-sync: check if ignore-file is readable and not a directory

lib/aur-repo
=> aur-repo: initialize dependencies array with zero length

lib/aur-sync, tests/issue/741
Due to `select_ignores()` using `FNR == NR`, if the ignore file (`igni`) is empty, no lines would be printed at all. In other words, `db_info` would be empty, and no targets from `aur repo -u` would be added.
Fixes #901
=> sync: fix --upgrades if --ignore is specified

lib/aur-query, man1/aur-query.1
In theory POST allows for an unlimited amount of packages per info-type request, because URI length limits do not need to be considered.
The behavior is controlled by the `AUR_QUERY_RPC_POST` variable, which enables HTTP POST when set to a positive value (defaults to 1).
Search-type requests still use HTTP GET, because each request can only contain a single package (removing the need to deal with URI length limits.)
Because of the changes above, the `AUR_QUERY_RPC` variable should now only point to the address of the AUR endpoint, e.g. https://aur.archlinux.org/rpc.
Closes #902
=> aur-query: add HTTP POST for info-type requests

Makefile, lib/aur-srcver, makepkg/aurutils.changelog
Some PKGBUILDs run commands outside of the package function, which causes `aur-srcver` to fail because the PKGBUILD is sourced with an empty environment (`PATH` is empty).
Allow the user to specify environment variables that can be preserved with `-E`.
Issue #898
=> srcver: add -E / --env

lib/aur-pkglist, lib/aur-query, makepkg/aurutils.changelog, man1/aur-query.1
=> query, pkglist: use `aurutils` user-agent

lib/aur-query, man1/aur-query.1
This should allow for better performance with `curl --parallel` (benchmarks?), and also allows `aur-query` to work with empty inputs if HTTP post is used (issue #706).
Since the number of packages per POST request can be much higher than with a GET request, introduce a new environment variable `AUR_QUERY_RPC_SPLITNO_POST` which defaults to 2000.
=> aur-query: split POST requests

lib/aur-repo-filter, lib/aur-sync, makepkg/aurutils.changelog, man1/aur-repo-filter.1
Also ensure the arguments are passed on both to `pacinfo` and `pacsift` (this step was missing for `--sysroot`).
=> aur-repo-filter: add --config

lib/aur-query, lib/aur-search, tests/issue/925
This ensures the output from each (search/info) request can be concatenated in a fixed order, i.e. the same order as the arguments provided.
Storing these results also allows to check them for errors directly in `aur-query`.
Closes #925
=> aur-query: store intermediary results

lib/aur-query, lib/aur-search, makepkg/aurutils.changelog, man1/aur-query.1
Unless `--raw` is specified, a formatted error message is displayed which can be propagated to other tools (specifically, `aur-search`).
Fixes #927
=> search: improve error handling

Makefile, lib/aur-sync, makepkg/PKGBUILD, makepkg/aurutils.changelog, man1/aur-sync.1
Example:
```
[custom]
package-foo
package-bar
[custom-testing]
package-baz
```
Targets from `--ignore` apply to the selected local repository as before.
=> aur-sync: add per-repository sections to --ignore-file

lib/aur-depends, man1/aur-depends.1
The `--graph` output is identical to the output from aur-graph(1), but resolved remotely. Used for e.g. piping into `aur-ninja` (see #908, #934).
=> depends: add --graph

lib/aur-query, tests/issue/938
=> query: abort if no query type is specified

lib/aur-sync
Using the number of remaining edges (%r) leads to an off-by-one in the
summary:
```
[0/2]  masterpassword-cli  [FAIL]
[1/2]  mkv-extractor-qt    [FAIL]
```
Use the number of started edges (%s) instead.
Closes #940
=> sync: use number of started edges

lib/aur-build
- adds `--nocheck` to `makechrootpkg_makepkg_args` so it can be passed to aur chroot
- fixes #942
=> build: pass --nocheck to chroot

lib/aur-query, makepkg/aurutils.changelog, man1/aur-query.1, tests/issue/938
When considering a "default" query type, we can make two observations:
1. `search`-type requests work both with HTTP POST and HTTP GET:
```
$ curl -d 'v=5' -d type='search' -d by='name' -d 'arg=aurutils' https://aur.archlinux.org/rpc
{"resultcount":2,"results": ...
```
2. aurweb has error-handling for invalid or missing type parameters:
```
$ curl -d 'v=5' -d type='foobar' -d by='name' -d 'arg=aurutils' https://aur.archlinux.org/rpc
{"error":"Incorrect request type specified.","resultcount":0,"results":[],"type":"error","version":5}
```
It thus makes sense to decouple GET and POST methods from the specific type of request. This way, a wrong (or missing) type is directly handled by aurweb. In addition, the default "by" search argument from aurweb no longer needs to be hardcoded in …
=> query: avoid hardcoding request types

man1/aur-sync.1
This summarizes the main tasks of `aur-sync`, and explains that it serves as an example program. The parts duplicated from `aur-view(1)` are also removed.
Closes #844
=> aur-sync.1: extend description

lib/aur-build, lib/aur-chroot, makepkg/aurutils.changelog, man1/aur-build.1, man1/aur-chroot.1
The `aur-chroot` command-line was changed so that `--create`, `--build` and `--update` can be used in a single command. Command-line arguments are now exclusively used for packages passed to `mkarchroot` and `arch-nspawn`.
To set `makechrootpkg` options, the new `--margs` and `--cargs` options are available. As `aur-build --margs`, these take a comma-delimited string and can be specified multiple times.
Closes #950, #807
=> chroot: use positional arguments for packages

lib/aur-srcver
The [previously used function `srcver_pkgbuild_info()`](https://github.com/AladW/aurutils/commit/257362fff5efc7d86b8ee6065eb7ab45c9e4e9bb#diff-1e8bf88edce180a3c750b38531053b933c7335473488fd78aa9c987c622ab462L7) changed the currently directory to `$n`  sourcing the PKGBUILD. Since switching to libmakepkg this does not happen any more, leading to the following error:
```
/usr/lib/aurutils/aur-srcver: line 103: PKGBUILD: No such file or directory
```
=> srcver: fix directory to source the build script from

lib/aur-view, makepkg/aurutils.changelog, man1/aur-view.1
`--revision` allows to use e.g. `FETCH_HEAD` for comparison purposes, to approve changes before merging them.
`--no-patch` can be useful when using `aur-view` with larger repositories.
=> `view`: add `--revision`, `--no-patch`

lib/aur-fetch
Invoking the pager needlessly interrupts/delays the command by forcing interactive action to close the pager.
=> aur-fetch: add --no-pager to the git log command

lib/aur-fetch, lib/aur-sync
In aur-sync, the `--no-build` option prints the paths of target packages.
With the recent addition of the `git log` check in aur-fetch in #960, the output
of `aur sync --no-build` has now become polluted with the `aur fetch` output from `git log`.
That makes the output of `aur sync --no-build` less usable when automating builds.
This PR redirects the `aur-fetch` output, which is purely diagnostic anyway, to standard error.
=> aur-sync: redirect aur-fetch output to stderr

lib/aur-build, lib/aur-sync, makepkg/aurutils.changelog, man1/aur-build.1
Closes #937
If anyone has a use-case for `aur-build --results` which can't be replicated in other ways, please mention it here.
=> aur-build: deprecate --results, fixups

aur.in, makepkg/aurutils.changelog, man1/aur.1
This is more convenient than changing environment variables globally (e.g. in ~/.bashrc, which is sourced by ~/.bash_profile), while not being as complex as a fully-fledged configuration system.
=> `aur`: load environment variables

lib/aur-pkglist, makepkg/aurutils.changelog, man1/aur-pkglist.1
This avoids a HTTP request when the file was retrieved before expiration of the TTL.
Before:
```
$ time aur pkglist --ttl 1800 >/dev/null 
real	0m0.121s
user	0m0.028s
sys	0m0.020s
```
After:
```
$ time ./aur-pkglist --ttl 1800 >/dev/null 
real	0m0.013s
user	0m0.014s
sys	0m0.000s
```
Issue #984
=> pkglist: check local timestamp against system time

lib/aur-search, makepkg/aurutils.changelog, man1/aur-search.1
When `--fmt-stdin` is set, JSON is taken directly from standard input, instead of from `aur-query`. This allows in particular to pipe aur-pkglist --info / --search output to aur-search.
For example, the following pipeline returns all orphan packages whose name starts in `r-`:
```bash
$ aur pkglist --info | jq -r '{
"results": [.[] |
select(.Maintainer == null) |
select(.Name | test("^r-"))
], "type": "search", "version": 5
}' | aur search --fmt-stdin
```
_(Arguably having a pipeline of generator and formatter is how things should have been in the first place.)_
This example originates from aurweb returning "Too many results" when querying an empty maintainer (orphan) search. [1] It could also be used for e.g. `provides` search:
```
$ aur pkglist --info | jq -r '.[] | select(.Provides[]? | …
```
=> search: add --fmt-stdin

lib/aur-search, makepkg/aurutils.changelog, man1/aur-search.1
These two options replace --fmt-stdin and allow more flexibility. For example, the pipeline given in 1633366b7d6f6cdf75deec37cec3aacae5e67c8e using jq(1) can be replaced with a faster awk(1) pipeline:
```bash
$ time aur pkglist --info | jq ... | aur search --stdin-json
real	0m2.661s
user	0m3.569s
sys	0m0.283s
$ time aur pkglist -- '^r-' | aur search -i --table - \
| awk -F\\t '{ if ($8 == "-") print; }' \
| aur search --stdin-table
real	0m0.725s
user	0m0.531s
sys	0m0.125s
```
=> search: add `--stdin-table`, rename `--fmt-stdin` -> `--stdin-json`

completions/zsh/_aur.zsh, lib/aur-search, makepkg/aurutils.changelog, man1/aur-search.1
The future `aur-format` will exclusively take JSON as standard input, and either print JSON or formatted output. Remove the `--stdin-table` option to reflect this.
Rename `--stdin-json` to `--json-stdin`, such that a tab-completion for `--json` shows both `--json` and `--json-stdin`.
=> search: remove --stdin-table, rename --stdin-json to --json-stdin

lib/aur-search
Issue #995
Alternative: always print the hyperlink, even with NO_COLOR=1. The `hyperlink` function is then reduced to:
```bash
hyperlink() {
local OSC8="\e]8" ST="\e\\"
printf "$OSC8;;%s$ST%s$OSC8;;$ST" "$1" "$2"
}
```
=> search: print package name once with NO_COLOR

lib/aur-fetch, lib/aur-sync, makepkg/aurutils.changelog, man1/aur-fetch.1, tests/issue/1007
* Do not ignore system configuration, i.e. in $HOME/.gitconfig
* Only run git-fetch by default
* Add --auto flag (shorthand for --sync=auto)
* Add -f flag (shorthand for --discard), i.e. aur fetch -Sf
* Remove deprecation notices
=> fetch: improve compatibility with aurutils <=9.6

lib/aur-sync, makepkg/aurutils.changelog
This allows to use shell substitution for `--ignore-file` (no random seek required) while still allowing to use per-repository ignores.
Closes #880
=> sync: use pkgspec for ignores instead of pacini

Makefile, lib/aur-build, makepkg/PKGBUILD, makepkg/aurutils.changelog, man1/aur-build.1
When using `sudoers(5)` to remove password prompts for select commands, `pacman --config=/tmp/...` command-lines are variable and thus require whitelisting `/usr/bin/pacman` (opening up `sudo pacman -U` and `sudo pacman --config`), or `--config` with arbitrary arguments (e.g. `--config=/tmp/bad.conf`).
Use a different mechanism to limit upgrades to the local repository, which uses fixed command-lines:
1. Propagate new databases with `pacsync custom`
2. Check if any installed packages are to be upgraded with `pacman -Quq`
3. Restrict the targets to the local repository with `pacsift --repo=custom`
4. Finally, install upgrades with `pacinstall --no-confirm`
For replacements, it suffices to use `pacinstall --resolve-replacements=none`. Compare the (unpublished) pacman commit: …
=> build: do not use generated configs for elevated commands

lib/aur-build, lib/aur-build--sync, makepkg/aurutils.changelog, man1/aur-build.1
Instead of prefixing several pacsync/pacman commands with `sudo`, wrap the commands in an `build--sync` helper. When configurating `sudoers` rules, this is more granular than blanket `pacsync` and `pacman` rules: only upgrading local repository targets is whitelisted.
Compared to the previous approach, `--pacman-conf` does not apply to local repository upgrades. This makes it harder to inadvertendly shoot yourself in the foot by passing on a potentially world-writeable file to a privileged process.
A helper can also be overridden through `AUR_EXEC_PATH`, and called by other scripts that wish to replicate a restrained local repository upgrade.
----
The idea of a separate helper to upgrade the local repository originates from issue #1012.
=> lib: add aur-build--sync helper

lib/aur-fetch, lib/aur-fetch--mirror, lib/aur-sync, makepkg/aurutils.changelog, man1/aur-fetch.1
Add machinery to support read-only mirrors of `aur.git`, such as https://github.com/archlinux/aur. The basic idea is inspired by `asp`:
1. Keep a shallow clone of `aur.git` (`git clone --depth=1`) in `AUR_ROOT` (defaults to `$XDG_CACHE_HOME/aur`)
2. Add remotes to package branches as needed
3. Run `git-fetch` to pull in new revisions for each branch
4. Create local clones for each branch, where each clone fetches from `+refs/remotes/orgin/<package>:refs/remotes/origin/<package>`
The last step ensures there is no mismatch between revisions in `aur.git` and branch `HEAD`s in the shallow clone. In other words, running `git-fetch` in the shallow clone followed by `git-pull` in the local branch clones suffices to update to new revisions. To filter out any invalid arguments, a list of all …
=> lib: add `aur-fetch--mirror`

completions/Makefile, completions/zsh/_aur, completions/zsh/_aur.zsh, completions/zsh/_aur_local_packages, completions/zsh/_aur_packages, completions/zsh/_aur_repositories
This adds support for extending zsh completion for third party aur commands. I have tested it with my own local `aur-rm`.
Some of the helpers (completing packages and repositories) have been made into auto loadable standalone functions so that they are accessible by third party completion scripts. This defines a new stable API and might thus need some thought about if that would present a problem.
=> Support extending zsh completion for third party commands

examples/README.md, examples/view-delta, lib/aur-view, makepkg/PKGBUILD, makepkg/aurutils.changelog, man1/aur-view.1
* Add a diagnostic if `aur-view` encounters an invalid revision
* Add `examples/view-delta` as alternative (read-only) review mechanism with `git-delta` and `bat`
* Change `exit 22` to `exit 2` on invalid arguments
=> view: improve diagnostics, add `view-delta`

lib/aur-build, man1/aur-build.1
`as_user` uses env(1) and will thus bypass any shell functions.
=> build: fix `MAKEPKG`

lib/aur-build, makepkg/aurutils.changelog
To run `aur-build` with elevated permissions, we currently have:
* For regular builds, an `aur-build` wrapper can handle dependency resolution as root and call `aur-build` unprivileged for the actual build. 
* For chroot builds, a wrapper is not immediate: a single elevated command, `aur-chroot`, is run in the middle of a series of unprivileged commands. Because of this, `aur-build` gained `as_user` / `setpriv`. (#907)
* The creation of `aur-build--sync` only leaves `aur-chroot` as privileged command in `aur-build`.
In other words, `as_user` has only a very narrow use case. `--dry-run` was never really used for anything, except potentially make a chroot wrapper possible. This PR removes both options.
----
In the future, a client/server approach can handle both unattended chroot and …
=> build: remove `as_user`, `--dry-run`

lib/aur-fetch, makepkg/aurutils.changelog, man1/aur-fetch.1
git-rebase expects a clean worktree, unlike git-merge.
Closes #1006
=> fetch: run git-checkout unconditionally with --rebase

man1/aur.1
fixed manpage suggesting a wrong jq directive to parse aur query, it reports a dictionary first, not an array
=> fixed manpage suggesting a wrong jq directive to parse aur query

examples/README.md, examples/build-asroot, makepkg/aurutils.changelog
This is a (customizable) replacement for the removed `AUR_ASROOT` functionality, aimed at host builds.
edit: this is a fair bit larger than the other example scripts - essentially a re-implementation of `aur-build` for specific purposes.
=> examples: add `build-asroot`

lib/aur-build, makepkg/aurutils.changelog, man1/aur-build.1
When multiple local repositories are configured, `aur-build -d <repo> -c` will require a pacman configuration named after <repo>. When a single pacman.conf suffices for all local repositories (e.g. when free-standing repositories are not a requirement), this implies copies or symbolic links for each repository.
To avoid this, fallback to `/etc/aurutils/pacman-<machine>.conf` if `/etc/aurutils/pacman-<repo>.conf` does not exist for a specified repository.
=> `build`: fallback to `pacman-<machine>.conf`

lib/aur-sync, lib/aur-view, makepkg/aurutils.changelog, man1/aur-view.1
This allows to distinguish source files for different packages when concatenating diffs, e.g. for use with `examples/view-delta`.
=> `view`: add `--prefix`

lib/aur-depends, lib/aur-sync, makepkg/aurutils.changelog
`RequiredBy` gives for every node in the dependency graph all predecessor node that depend on it. The `--assume-installed` flag removes all specified targets from the graph, as well as from all `RequiredBy` arrays. This is done by scanning the targets for every reverse dependency.
When afterwards a node has an empty `RequiredBy` array, it is considered as no longer required and removed from the dependency graph. As a result, dependencies for `--assume-installed` targets are also removed from the graph. All this is done after `provides` are solved (`chain_mod`) unless `--no-provides` is supplied.
A direct use for this is expanding `aur-sync --ignore` to also remove dependencies of ignored targets. Later changes could use a similar mechanism to remove transitive dependencies for …
=> `depends`: add `--assume-installed`

docker/Dockerfile
Hi!
The Dockerfile placed at "docker/Dockerfile" contains the best practice violation [DL3048](https://github.com/hadolint/hadolint/wiki/DL3048) detected by the [hadolint](https://github.com/hadolint/hadolint) tool.
The smell DL3048 occurs when the pattern used for the label keys does not match the format recommended by official guidelines.
In this pull request, we propose a fix for that smell generated by our fixing tool. We verified that the patch is correct before opening the pull request.
To fix this smell, specifically, the label keys are refactored to match the correct format.
This change is only aimed at fixing that specific smell. In the case the fix is not valid or useful, please briefly indicate the reason along with suggestions for possible improvements.
Thanks in advance.
=> Fix for Dockerfile smell DL3048

lib/aur-sync
This enables the usage of aur-sync as normal user without sudo permission.
=> Add support to pass --no-sync option to aur-build command

lib/aur-sync
=> sync: `--rebuild-tree` implies `--no-provides`

lib/aur-chroot, makepkg/aurutils.changelog
The paths differ for the devtools used before and after the git migration.
Closes #1072
=> `chroot`: use conditional default paths

lib/aur-sync
`/dev/stdout` is not handled specifically and writeable by the owner of the pseudoterminal. When running the script as a different user, it may thus not have write access. See:
https://unix.stackexchange.com/a/38580
Fixes #1083
=> `sync`: do not use /dev/stdout

examples/sync-rebuild
This allows to regenerate `.SRCINFO` for packages with a `pkgver` function, so that a correct comparison between `.SRCINFO` and local repository package can be made.
=> `sync-rebuild`: add `--vcs`

lib/aur-depends, makepkg/aurutils.changelog, tests/depends
This allows to more easily iterate over the (reverse) dependency graph without taking dependency types into account.
=> `depends`: use flat dictionary for `RequiredBy`

lib/aur-build--pkglist
This avoids doing the wrong thing if a PKGBUILD happens to be somewhere in $PATH, in which case a `source PKGBUILD` will load it instead of the one in $PWD.
Fixes #1115.
=> `build--pkglist`: load PKGBUILD by absolute path

README.md
First of all, thank you for your work! I use `aurutils` every day.
I wanted to contribute to smooth the adoption process for newcomers. The previous `USAGE` section of `README.md` had a few minor shortcomings (in my opinion):
1. It links to the source code of the [`aur(1)`](man1/aur.1) man page, which is hardly readable. 
2. It refers to `aur(1)` for installation instructions, but these are reported in a section at the very end of the page. Therefore, they can be missed easily.
This commit tries to address the above, by;
1. Adding the explicit bash command to open the manual.
2. Adding the name of the manual section where the instructions are located, so that they can be found easily.
=> readme: Better explain where to find setup instructions

Makefile, lib/aur-depends, lib/aur-sync, makepkg/aurutils.changelog, man1/aur-depends.1, perl/AUR/Depends.pm, perl/AUR/Json.pm, perl/AUR/Options.pm, perl/AUR/Query.pm, perl/t/depends.t, tests/package
This will allow to have a common interface between `aur-graph` and `aur-depends`, such that local .SRCINFO files can be handled similar to packages available on the AUR.
It also adds checking version requirements with `aur-depends`, which was previously only available in `aur-graph`.
The tests are severely lacking at this point, although all the cases in `test/package` pass.
=> `perl`: add `Depends.pm`

man1/aur-view.1
The `.BR` macro seems to eliminate all spaces between words.
=> Fix formating of aur-view(1) manual

lib/aur-graph
Some small helper packages on the AUR are entirely self-hosted, i.e. they have no dedicated upstream URL outside the AUR.
Those packages deliver everything they need in and alongside the PKGBUILD, so authors of these packages may choose to *self-reference* their own AUR page in the `url` field.
Examples for such packages with self-referential `url` fields are the pkgbases [what-is-electron](https://aur.archlinux.org/cgit/aur.git/tree/.SRCINFO?h=what-is-electron) and [electron-blur-me-not](https://aur.archlinux.org/cgit/aur.git/tree/.SRCINFO?h=electron-blur-me-not):
```properties
pkgbase = what-is-electron
pkgdesc = Point /usr/bin/electron to any Electron version you like
pkgver = 0.1.0
pkgrel = 1
url = https://aur.archlinux.org/pkgbase/what-is-electron
```
Because those `url` fields may …
=> `graph`: prevent unwanted matches in certain URLs

lib/aur-build, lib/aur-sync, makepkg/aurutils.changelog, man1/aur-build.1, man1/aur-sync.1, man1/aur.1
This makes `--clean` optional and exposes `--cleanbuild` directly without needing to resort to `--margs`. To compensate for the additional storage, add `-d` to `git clean` in the `aur-gc` example.
=> `sync`: make `--clean` optional

lib/aur-repo, makepkg/aurutils.changelog
Consider a script `aur-repo-init`, which aims to create a local repository by the file paths defined in pacman.conf. With a file/directory check in place, `aur-repo` would fail to print the necessary paths, even though the repository is not directly accessed.
Remove the checks to address this use case. Necessary file checks are still done by `aur-repo-parse`, when actually reading from the local repository. The same holds for `aur-build` for write access.
Reported-by: Ivan Shapovalov <intelfx@intelfx.name>
=> repo: remove explicit file/directory checks

man1/aur-chroot.1
Otherwise you'd get 'read-only filesystem' errors when trying to build.
=> docs: ccache with aur-chroot needs --bind-rw

lib/aur-repo-parse, tests/issue/1158
`"Repository":"core.db"` -> `"Repository":"core"`
Fixes: a3b6027b ("Repo.pm: add parse_db_file()")
Fixes: #1158
=> `repo-parse`: do not emit repo filename suffix for "Repository" key

lib/aur-depends, perl/AUR/Depends.pm, perl/t/depends.t
And some general refactoring. Maybe the high-level `get()` should be renamed to `solve()`, with `extract()` renamed to something else (`recurse()`?)
=> Depends.pm: warn about targets that are not found

lib/aur-graph, lib/aur-sync, makepkg/aurutils.changelog
Optdepends have both a package name and a description, separated by a colon. Take this into account. Additionally, make aur-sync preserve the exit status from `aur-graph`.
=> `graph`: fix handling of `optdepends`

lib/aur-repo, makepkg/aurutils.changelog
In #1110 a mandatory check was added for the local repository to be configured in pacman.conf. However, the bulk of the aur-repo functionality is available without configuration in pacman.conf, provided the repository root (`--root`) is specified by the user.
@BrainDamage
=> repo: warn when local repo is not configured

lib/aur-sync, lib/aur-view, makepkg/aurutils.changelog
This moves the `git orderFile` logic from `aur-sync` to `aur-view`. Incidentally this was the only remaining `git` call in `aur-sync`.
Calling `git config diff.orderFile` on every `aur-view` call, instead of after a `git clone`, ensures `orderFile` always points to a valid path. For example, if `HOME=/temphome/user` aur sync ...` is run for a series of new(ly cloned) packages, subsequent calls `aur sync ...` using the default `HOME=/home/user` value would still rely on the orderFile in `/temphome/user`. This leads to errors if the path is deleted.
Closes #1167
=> view: set orderFile on every call

lib/aur-chroot, makepkg/aurutils.changelog
This matches `aur-repo` behavior. In addition, if $directory/root is existing, print `there is nothing to do` with `--create`.
=> chroot: make --status default if no modes are specified

lib/aur-chroot
Avoid triggering the implied `--status` when `--path` is given.
Fixes: 3c282892 ("chroot: make --status default if no modes are specified")
=> chroot: unbreak `--path`

lib/aur-build, lib/aur-sync, makepkg/aurutils.changelog, man1/aur-build.1, man1/aur-sync.1
This uses a separate gpg keyring for signature verification with `makepkg(8)`. Since this will not affect the default keyring, the behavior is enabled by default.
Closes #1129.
=> `sync`: automatic `gnupg` key retrieval

Makefile, lib/pacman/aur-build, makepkg/aurutils.changelog
This was introduced in commit 26409db to avoid log files ending up in /var/tmp. However, PKGDEST ostensibly has no effect on LOGDEST in later pacman versions.
https://github.com/aurutils/aurutils/issues/1196#issuecomment-2926600742
=> `build`: do not define `LOGDEST` explicitly

Makefile, completions/Makefile, completions/command_opts.sh
Got this error while building the latest PKGBUILD from aur:
```
==> Validating source files with sha256sums...
aurutils-20.5.tar.gz ... Passed
==> Extracting sources...
-> Extracting aurutils-20.5.tar.gz with bsdtar
==> Starting build()...
sed -e 's|AURUTILS_LIB_DIR|/usr/lib/aurutils|' \
-e 's|AURUTILS_VERSION|20.5|' aur.in >aur
make[1]: Entering directory '/home/user/src/pkgbuilds/aurutils/src/aurutils-20.5/completions'
bash bash/aurutils.in >bash/aur
bash: ../lib/aur-build: No such file or directory
bash: ../lib/aur-chroot: No such file or directory
bash: ../lib/aur-fetch: No such file or directory
bash: ../lib/aur-pkglist: No such file or directory
bash: ../lib/aur-repo: No such file or directory
bash: ../lib/aur-repo-filter: No such file or directory
bash: ../lib/aur-srcver: No such …
```
=> Fix bash completion

makepkg/aurutils.changelog, man1/aur-fetch.1, man1/aur-sync.1
With the current wording users might expect aurutils to accept values like `true`. This change concretizes it to integers.
=> Concretize what aurutils sees as a positive value

man1/aur-build.1
Without this, the formatting of the `AUR_PACMAN_BUILD` environment variable was incorrect.
=> Add missing section header declaration to aur-build man page

man1/aur-build.1
This seems to the be the missing piece to make convenient use of a separate build user.
=> aur-build.1: example for setfacl

lib/aurweb/aur-fetch, tests/parseopt-consistency
Support both pkgbase names and urls given via stdin or on the command-line.
This is done by prefixing pkgbases with AUR_LOCATION and capturing the basename of paths from urls. Each pkgbase and url is then associated together so that the main loop can use the remote url specified for each given package.
This commit introduces a requirement on trurl(1) which is used to accurately parse out url path components.
Addresses https://github.com/aurutils/aurutils/issues/1104
=> aur-fetch: support mixed url and pkgbase names

lib/pacman/aur-build, makepkg/aurutils.changelog, man1/aur-build.1
This matches `repose --pool` as discussed in #1213. I'm not entirely sure on use-cases for this option, but the implementation is short enough.
The ugly part is file systems that don't support symbolic links. This could be checked beforehand with something like:
```bash
support_symlink() {
env -C "$1" perl -e 'print eval {symlink("",""); 1};'
}
if [[ $db_root != "$db_pool" ]] && (( ! $(support_symlink "$db_root") )); then
printf 'warning: --pool: repository root %s does not support symlinks' "$db_pool"
fi
```
=> `build`: add `--pool`
